/** Generated by scripts/build-cloud-functions.js — do not edit. */
"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// packages/room-contracts/index.js
var require_room_contracts = __commonJS({
  "packages/room-contracts/index.js"(exports2, module2) {
    "use strict";
    var PROTOCOL_VERSION = 2;
    var SCHEMA_VERSION = 2;
    var MAX_SEATS = 6;
    var LIFECYCLE = {
      LOBBY: "LOBBY",
      ACTIVE: "ACTIVE",
      DISSOLVED: "DISSOLVED"
    };
    var COMMAND_TYPES = {
      CREATE_ROOM: "CREATE_ROOM",
      JOIN_ROOM: "JOIN_ROOM",
      LEAVE_ROOM: "LEAVE_ROOM",
      REORDER_SEATS: "REORDER_SEATS",
      DISSOLVE_ROOM: "DISSOLVE_ROOM",
      UPDATE_MEMBER_PROFILE: "UPDATE_MEMBER_PROFILE",
      // Partner
      SUBMIT_SCORE: "SUBMIT_SCORE",
      START_STATEMENT: "START_STATEMENT",
      ADVANCE_TURN: "ADVANCE_TURN",
      POST_MESSAGE: "POST_MESSAGE",
      SUBMIT_CLOSING_VOTE: "SUBMIT_CLOSING_VOTE",
      APPEND_ARTIFACT: "APPEND_ARTIFACT",
      // Spy（Phase 6）
      SPY_START_ASSIGN: "SPY_START_ASSIGN",
      SPY_GET_MY_CARD: "SPY_GET_MY_CARD",
      SPY_START_SPEAK: "SPY_START_SPEAK",
      SPY_ADVANCE_SPEAKER: "SPY_ADVANCE_SPEAKER",
      SPY_SUBMIT_VOTE: "SPY_SUBMIT_VOTE",
      SPY_CONFIRM_RESULT: "SPY_CONFIRM_RESULT",
      SPY_NEXT_ROUND: "SPY_NEXT_ROUND",
      SPY_CONTINUE: "SPY_CONTINUE",
      SPY_RESTART: "SPY_RESTART"
    };
    var ERR = {
      INVALID_ARGUMENT: "INVALID_ARGUMENT",
      UNAUTHENTICATED: "UNAUTHENTICATED",
      ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
      ROOM_FULL: "ROOM_FULL",
      NOT_MEMBER: "NOT_MEMBER",
      HOST_REQUIRED: "HOST_REQUIRED",
      HOST_CANNOT_LEAVE: "HOST_CANNOT_LEAVE",
      SESSION_MISMATCH: "SESSION_MISMATCH",
      REVISION_CONFLICT: "REVISION_CONFLICT",
      INVALID_TRANSITION: "INVALID_TRANSITION",
      COMMAND_ID_CONFLICT: "COMMAND_ID_CONFLICT",
      COMMAND_IN_PROGRESS: "COMMAND_IN_PROGRESS",
      RATE_LIMITED: "RATE_LIMITED",
      DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
      INTERNAL_ERROR: "INTERNAL_ERROR",
      ROOM_DISSOLVED: "ROOM_DISSOLVED",
      SELF_SCORE: "SELF_SCORE",
      ALREADY_VOTED: "ALREADY_VOTED",
      NOT_ENOUGH_PLAYERS: "NOT_ENOUGH_PLAYERS",
      GAME_IN_PROGRESS: "GAME_IN_PROGRESS",
      NO_CARD: "NO_CARD",
      NO_WORD_PAIR: "NO_WORD_PAIR"
    };
    var ERR_MSG = {
      [ERR.INVALID_ARGUMENT]: "\u53C2\u6570\u4E0D\u5408\u6CD5",
      [ERR.UNAUTHENTICATED]: "\u672A\u767B\u5F55",
      [ERR.ROOM_NOT_FOUND]: "\u623F\u95F4\u4E0D\u5B58\u5728",
      [ERR.ROOM_FULL]: "\u623F\u95F4\u5DF2\u6EE1",
      [ERR.NOT_MEMBER]: "\u975E\u623F\u95F4\u6210\u5458",
      [ERR.HOST_REQUIRED]: "\u4EC5\u623F\u4E3B\u53EF\u64CD\u4F5C",
      [ERR.HOST_CANNOT_LEAVE]: "\u623F\u4E3B\u8BF7\u4F7F\u7528\u89E3\u6563\u623F\u95F4",
      [ERR.SESSION_MISMATCH]: "\u573A\u6B21\u5DF2\u53D8\u66F4",
      [ERR.REVISION_CONFLICT]: "\u623F\u95F4\u72B6\u6001\u5DF2\u66F4\u65B0",
      [ERR.INVALID_TRANSITION]: "\u5F53\u524D\u6B65\u9AA4\u4E0D\u5141\u8BB8\u8BE5\u64CD\u4F5C",
      [ERR.COMMAND_ID_CONFLICT]: "commandId \u51B2\u7A81",
      [ERR.COMMAND_IN_PROGRESS]: "\u547D\u4EE4\u5904\u7406\u4E2D",
      [ERR.RATE_LIMITED]: "\u8BF7\u6C42\u8FC7\u4E8E\u9891\u7E41",
      [ERR.DEPENDENCY_UNAVAILABLE]: "\u4F9D\u8D56\u6682\u65F6\u4E0D\u53EF\u7528",
      [ERR.INTERNAL_ERROR]: "\u670D\u52A1\u5F02\u5E38",
      [ERR.ROOM_DISSOLVED]: "\u623F\u95F4\u5DF2\u89E3\u6563",
      [ERR.SELF_SCORE]: "\u5F53\u524D\u51FA\u724C\u73A9\u5BB6\u65E0\u9700\u6253\u5206",
      [ERR.ALREADY_VOTED]: "\u60A8\u5DF2\u8868\u6001",
      [ERR.NOT_ENOUGH_PLAYERS]: "\u4EBA\u6570\u4E0D\u8DB3",
      [ERR.GAME_IN_PROGRESS]: "\u672C\u5C40\u5DF2\u5728\u8FDB\u884C\u4E2D",
      [ERR.NO_CARD]: "\u5C1A\u672A\u5206\u914D\u8EAB\u4EFD",
      [ERR.NO_WORD_PAIR]: "\u8BCD\u5E93\u4E3A\u7A7A"
    };
    function fail(errCode, errMsg, extra) {
      return {
        ok: false,
        errCode,
        errMsg: errMsg || ERR_MSG[errCode] || errCode,
        retryable: errCode === ERR.DEPENDENCY_UNAVAILABLE || errCode === ERR.COMMAND_IN_PROGRESS,
        ...extra || {}
      };
    }
    function okResult(fields) {
      return { ok: true, ...fields || {} };
    }
    function isNonEmptyString(v) {
      return typeof v === "string" && v.trim().length > 0;
    }
    function isCommandId(v) {
      return typeof v === "string" && v.trim().length >= 4 && v.trim().length <= 64;
    }
    function validateCommandEnvelope(raw) {
      if (!raw || typeof raw !== "object") {
        return fail(ERR.INVALID_ARGUMENT, "command envelope \u5FC5\u586B");
      }
      const type = raw.type;
      if (!Object.prototype.hasOwnProperty.call(COMMAND_TYPES, type) && !Object.values(COMMAND_TYPES).includes(type)) {
        return fail(ERR.INVALID_ARGUMENT, `\u672A\u77E5\u547D\u4EE4\u7C7B\u578B: ${type}`);
      }
      if (!isCommandId(raw.commandId)) {
        return fail(ERR.INVALID_ARGUMENT, "commandId \u5FC5\u586B");
      }
      const protocolVersion = raw.protocolVersion == null ? PROTOCOL_VERSION : Number(raw.protocolVersion);
      if (protocolVersion !== PROTOCOL_VERSION) {
        return fail(ERR.INVALID_ARGUMENT, `\u4EC5\u652F\u6301 protocolVersion=${PROTOCOL_VERSION}`);
      }
      if (type !== COMMAND_TYPES.CREATE_ROOM && !isNonEmptyString(raw.roomId)) {
        return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
      }
      const needsRevision = type !== COMMAND_TYPES.CREATE_ROOM && type !== COMMAND_TYPES.JOIN_ROOM && type !== COMMAND_TYPES.SUBMIT_SCORE && type !== COMMAND_TYPES.POST_MESSAGE && type !== COMMAND_TYPES.SUBMIT_CLOSING_VOTE && type !== COMMAND_TYPES.APPEND_ARTIFACT && type !== COMMAND_TYPES.SPY_GET_MY_CARD && type !== COMMAND_TYPES.SPY_SUBMIT_VOTE;
      if (needsRevision) {
        if (raw.expectedRevision == null || !Number.isFinite(Number(raw.expectedRevision))) {
          return fail(ERR.INVALID_ARGUMENT, "expectedRevision \u5FC5\u586B");
        }
      }
      return okResult({
        envelope: {
          protocolVersion: PROTOCOL_VERSION,
          roomId: raw.roomId ? String(raw.roomId).trim() : "",
          sessionId: raw.sessionId || null,
          commandId: String(raw.commandId),
          expectedRevision: raw.expectedRevision == null ? null : Number(raw.expectedRevision),
          type,
          payload: raw.payload && typeof raw.payload === "object" ? raw.payload : {},
          clientSentAt: raw.clientSentAt != null ? Number(raw.clientSentAt) : null
        }
      });
    }
    function emptyDomainRevisions() {
      return {
        members: 0,
        session: 0,
        scores: 0,
        contributions: 0,
        artifacts: 0,
        messages: 0,
        votes: 0
      };
    }
    module2.exports = {
      PROTOCOL_VERSION,
      SCHEMA_VERSION,
      MAX_SEATS,
      LIFECYCLE,
      COMMAND_TYPES,
      ERR,
      ERR_MSG,
      fail,
      okResult,
      validateCommandEnvelope,
      emptyDomainRevisions,
      isNonEmptyString
    };
  }
});

// packages/room-domain/spyWordPairs.js
var require_spyWordPairs = __commonJS({
  "packages/room-domain/spyWordPairs.js"(exports2, module2) {
    var WORD_ENTRIES = [
      { word: "\u5F00\u5173", blurb: "\u63A7\u4EF6 0/1 \u72B6\u6001\u76F4\u63A5\u5BF9\u5E94\u7269\u4EF6\u72B6\u6001\uFF0C\u72B6\u6001\u4E0D\u53D8\u5219\u7269\u4EF6\u4E0D\u53D8\uFF0C\u4E0D\u5173\u5FC3\u52A8\u4F5C\u8FC7\u7A0B\u3002" },
      { word: "\u5355\u51FB", blurb: "\u9700\u5B8C\u6210\u6309\u4E0B\u518D\u62AC\u8D77\uFF080\u21921\u21920\uFF09\u624D\u89E6\u53D1\u4E00\u6B21\uFF0C\u4E0D\u7559\u5B58\u72B6\u6001\uFF0C\u62AC\u8D77\u65F6\u751F\u6548\u3002" },
      { word: "\u6309\u4E0B", blurb: "\u6355\u6349\u4ECE 0\u21921 \u7684\u77AC\u65F6\u53D8\u5316\u5373\u89E6\u53D1\uFF0C\u4E0D\u8981\u6C42\u62AC\u8D77\uFF0C\u4E5F\u4E0D\u7559\u5B58\u72B6\u6001\u3002" },
      { word: "\u6ED1\u52A8\u5207\u6362", blurb: "\u4F4D\u79FB\u8FBE\u5230\u9608\u503C\u7ACB\u523B\u8DF3\u8F6C\u72B6\u6001\uFF0C\u65E0\u9700\u91CA\u653E\uFF0C\u5BF9\u8C61\u4E0D\u5168\u7A0B\u5B9E\u65F6\u8DDF\u968F\u3002" },
      { word: "\u8F7B\u626B\u5207\u6362", blurb: "\u4F4D\u79FB\u8FBE\u6807\u4E14\u677E\u624B\u91CA\u653E\u540E\u624D\u5207\u6362\uFF0C\u652F\u6301\u4E2D\u9014\u53CD\u5411\u53D6\u6D88\uFF0C\u5F3A\u8C03\u786E\u8BA4\u4E0E\u5BB9\u9519\u3002" },
      { word: "\u8D8A\u754C\u5207\u6362", blurb: "\u4EE5\u7A7F\u8FC7\u8FB9\u754C\u7EBF\u4E3A\u552F\u4E00\u5224\u5B9A\uFF0C\u5212\u8FC7\u77AC\u95F4\u89E6\u53D1\uFF0C\u4E0D\u770B\u603B\u4F4D\u79FB\u3001\u4E0D\u9700\u8981\u91CA\u653E\u3002" },
      { word: "\u5FEB\u51FB", blurb: "\u8C03\u548C\u5355\u51FB\u4E0E\u957F\u6309\uFF1A\u5FEB\u901F\u6309\u4E0B\u5E76\u62AC\u8D77\u5224\u5355\u51FB\uFF0C\u6309\u4F4F\u8FC7\u4E45\u5219\u5224\u957F\u6309\u3002" },
      { word: "\u70B9\u51FB\u7F13\u51B2", blurb: "\u8C03\u548C\u5355\u51FB\u4E0E\u53CC\u51FB\uFF1A\u9996\u6B21\u70B9\u51FB\u540E\u5EF6\u8FDF\u7B49\u5F85\uFF0C\u7A97\u53E3\u5185\u6709\u7B2C\u4E8C\u51FB\u5219\u53CC\u51FB\uFF0C\u5426\u5219\u5355\u51FB\u3002" },
      { word: "\u62D6\u62FD", blurb: "\u4EC5\u7531\u4F4D\u7F6E\u9A71\u52A8\uFF0C\u5B9E\u65F6\u8DDF\u968F\u3001\u65E0\u60EF\u6027\u3001\u65E0\u951A\u70B9\u5F52\u4F4D\uFF0C\u677E\u624B\u5373\u505C\u3002" },
      { word: "\u7529\u52A8", blurb: "\u4F4D\u7F6E\u52A0\u91CA\u653E\u901F\u5EA6\u9A71\u52A8\uFF0C\u91CA\u653E\u540E\u60EF\u6027\u6ED1\u884C\uFF0C\u7EC8\u70B9\u4E0D\u56FA\u5B9A\u3002" },
      { word: "\u7FFB\u52A8", blurb: "\u4F4D\u79FB\u53EF\u8DDF\u968F\uFF0C\u91CA\u653E\u540E\u5F3A\u5236\u5438\u9644\u5230\u9884\u8BBE\u951A\u70B9\uFF0C\u5F3A\u8C03\u7ED3\u679C\u786E\u5B9A\u3002" },
      { word: "\u6301\u7EED\u89E6\u53D1", blurb: "\u6309\u4F4F\u5373\u5F00\u59CB\uFF0C\u4EE5\u56FA\u5B9A\u95F4\u9694\u5300\u901F\u8FDE\u53D1\uFF0C\u65E0\u5EF6\u65F6\u95E8\u69DB\u3002" },
      { word: "\u957F\u6309", blurb: "\u6309\u4F4F\u8D85\u8FC7\u65F6\u95F4\u9608\u503C\u624D\u89E6\u53D1\u4E00\u6B21\uFF0C\u4E0D\u8FDE\u53D1\uFF0C\u7528\u5EF6\u8FDF\u964D\u4F4E\u8BEF\u89E6\u3002" },
      { word: "\u7F13\u51B2\u8FDE\u53D1", blurb: "\u6309\u4E0B\u5148\u7ACB\u5373\u89E6\u53D1\u4E00\u6B21\uFF0C\u7F13\u51B2\u7B49\u5F85\u540E\u518D\u8FDB\u5165\u8FDE\u7EED\u8FDE\u53D1\u3002" },
      { word: "\u591A\u70B9\u6709\u5E8F\u70B9\u51FB", blurb: "\u6309\u9884\u8BBE\u5148\u540E\u987A\u5E8F\u70B9\u51FB\u591A\u4E2A\u70B9\u4F4D\u5373\u53EF\uFF0C\u4E0D\u5F3A\u8C03\u70B9\u4F4D\u76F8\u5BF9\u65B9\u4F4D\u3002" },
      { word: "\u5F02\u4F4D\u8FDE\u89E6", blurb: "\u4EE5\u524D\u4E00\u70B9\u4E3A\u951A\uFF0C\u540E\u4E00\u70B9\u7684\u76F8\u5BF9\u65B9\u4F4D/\u8DDD\u79BB\u51B3\u5B9A\u8BED\u4E49\uFF0C\u987A\u5E8F\u4E0E\u7A7A\u95F4\u5171\u540C\u7EA6\u675F\u3002" }
    ];
    var PAIR_GROUPS = [
      ["\u5F00\u5173", "\u5355\u51FB", "\u6309\u4E0B"],
      ["\u6ED1\u52A8\u5207\u6362", "\u8F7B\u626B\u5207\u6362", "\u8D8A\u754C\u5207\u6362"],
      ["\u5FEB\u51FB", "\u70B9\u51FB\u7F13\u51B2"],
      ["\u62D6\u62FD", "\u7529\u52A8", "\u7FFB\u52A8"],
      ["\u6301\u7EED\u89E6\u53D1", "\u957F\u6309", "\u7F13\u51B2\u8FDE\u53D1"],
      ["\u591A\u70B9\u6709\u5E8F\u70B9\u51FB", "\u5F02\u4F4D\u8FDE\u89E6"]
    ];
    var ENTRY_MAP = WORD_ENTRIES.reduce((acc, item) => {
      acc[item.word] = item;
      return acc;
    }, {});
    function buildPairsFromGroups() {
      const pairs = [];
      let id = 1;
      PAIR_GROUPS.forEach((group) => {
        for (let i = 0; i < group.length; i += 1) {
          for (let j = i + 1; j < group.length; j += 1) {
            const a = ENTRY_MAP[group[i]];
            const b = ENTRY_MAP[group[j]];
            if (!a || !b) continue;
            pairs.push({
              id: `ixdl-${id}`,
              wordA: a.word,
              blurbA: a.blurb,
              wordB: b.word,
              blurbB: b.blurb
            });
            id += 1;
          }
        }
      });
      return pairs;
    }
    var SPY_WORD_PAIRS = buildPairsFromGroups();
    function pickRandomWordPair() {
      if (!SPY_WORD_PAIRS.length) return null;
      const pair = SPY_WORD_PAIRS[Math.floor(Math.random() * SPY_WORD_PAIRS.length)];
      const swap = Math.random() < 0.5;
      return {
        id: pair.id,
        civilianWord: swap ? pair.wordB : pair.wordA,
        civilianBlurb: swap ? pair.blurbB : pair.blurbA,
        spyWord: swap ? pair.wordA : pair.wordB,
        spyBlurb: swap ? pair.blurbA : pair.blurbB
      };
    }
    module2.exports = {
      SPY_WORD_PAIRS,
      pickRandomWordPair,
      WORD_ENTRIES
    };
  }
});

// packages/room-domain/spy.js
var require_spy = __commonJS({
  "packages/room-domain/spy.js"(exports2, module2) {
    "use strict";
    var {
      COMMAND_TYPES,
      ERR,
      fail,
      okResult
    } = require_room_contracts();
    var { pickRandomWordPair: pickLibraryWordPair } = require_spyWordPairs();
    var SPY_PHASE = {
      INTRO: "intro",
      ASSIGN: "assign",
      SPEAK: "speak",
      VOTE: "vote",
      RESULT: "result",
      NEXT_ROUND: "nextRound",
      SETTLE: "settle"
    };
    var SPY_PAGE = {
      intro: "spymodeindex",
      assign: "spyassign",
      speak: "spyspeak",
      vote: "spyvote",
      result: "spyresult",
      nextRound: "spynextround",
      settle: "spysettle"
    };
    var MIN_PLAYERS = 3;
    var SPEAK_ROUND_MS = 5 * 60 * 1e3;
    var SPEAK_TURN_MS = 60 * 1e3;
    var VOTE_ROUND_MS = 2 * 60 * 1e3;
    var DEFAULT_WORD_PAIRS = null;
    function pageForPhase(phase) {
      return SPY_PAGE[phase] || SPY_PAGE.intro;
    }
    function getDefaultSpyCount(playerCount) {
      const n = Number(playerCount) || 0;
      if (n < 3) return 0;
      if (n <= 6) return 1;
      return 2;
    }
    function shuffle(list, random) {
      const rnd = typeof random === "function" ? random : Math.random;
      const arr = list.slice();
      for (let i = arr.length - 1; i > 0; i -= 1) {
        const j = Math.floor(rnd() * (i + 1));
        const tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
      }
      return arr;
    }
    function pickDefaultWordPair() {
      if (typeof pickLibraryWordPair === "function") {
        return pickLibraryWordPair();
      }
      return null;
    }
    function samePlayerIndex(a, b) {
      if (a == null || b == null) return false;
      return Number(a) === Number(b);
    }
    function indexIncludes(list, index) {
      if (!Array.isArray(list) || index == null) return false;
      const n = Number(index);
      return list.some((item) => Number(item) === n);
    }
    function getAliveIndexSet(players) {
      return new Set(
        (players || []).filter((p) => p && p.alive !== false && p.leftRoom !== true).map((p) => Number(p.playerIndex))
      );
    }
    function findSpeakIndex(order, players, from) {
      const alive = getAliveIndexSet(players);
      const list = order || [];
      let i = Math.max(0, Number(from) || 0);
      while (i < list.length && !alive.has(Number(list[i]))) {
        i += 1;
      }
      return i;
    }
    function listPlayableMembers(room) {
      const seatMap = room.seatMap || {};
      const byUser = room.membersByUserId || {};
      return Object.keys(seatMap).map((seat) => {
        const userId = seatMap[seat];
        const m = byUser[userId];
        if (!userId || !m) return null;
        return {
          userId,
          seatNo: Number(seat),
          playerIndex: Number(seat),
          nickName: m.nickName || `\u73A9\u5BB6${seat}`,
          avatarUrl: m.avatarUrl || null,
          avatarIndex: m.avatarIndex != null ? m.avatarIndex : null
        };
      }).filter(Boolean).sort((a, b) => a.seatNo - b.seatNo);
    }
    function emptyVoteStatus() {
      return {
        votedPlayerIndexes: [],
        abstainPlayerIndexes: [],
        tally: {},
        ballots: {}
      };
    }
    function assignmentsMap(room) {
      if (room.spyAssignments && typeof room.spyAssignments === "object") {
        return room.spyAssignments;
      }
      const secrets = room.secretsByUserId || {};
      const out = {};
      Object.keys(secrets).forEach((userId) => {
        const row = secrets[userId];
        if (!row) return;
        const seat = row.playerIndex != null ? String(row.playerIndex) : null;
        if (seat) out[seat] = { ...row, userId };
      });
      return out;
    }
    function resolveWinnerSide(players) {
      const alive = (players || []).filter((p) => p && p.alive !== false);
      const spies = alive.filter((p) => p.role === "spy");
      const civilians = alive.filter((p) => p.role === "civilian");
      if (spies.length === 0) return "civilian";
      if (spies.length >= civilians.length) return "spy";
      return null;
    }
    function buildRevealList(spyGame, assignments) {
      return (spyGame.players || []).filter((p) => p && p.leftRoom !== true).map((p) => {
        const card = assignments[String(p.playerIndex)] || {};
        return {
          playerIndex: p.playerIndex,
          name: p.name || card.name || `\u73A9\u5BB6${p.playerIndex}`,
          role: card.role || null,
          word: card.word || null,
          alive: p.alive !== false
        };
      });
    }
    function beginSpeakPhase(spyGame, speakOrder, now) {
      const order = speakOrder || spyGame.speakOrder || [];
      const first = findSpeakIndex(order, spyGame.players, 0);
      return {
        ...spyGame,
        phase: SPY_PHASE.SPEAK,
        speakOrder: order,
        currentSpeakIndex: first,
        speakRoundStartedAt: now,
        speakTurnStartedAt: first < order.length ? now : 0,
        speakTurnMs: spyGame.speakTurnMs || SPEAK_TURN_MS,
        voteStartedAt: 0,
        voteStatus: emptyVoteStatus()
      };
    }
    function beginVotePhase(spyGame, now) {
      return {
        ...spyGame,
        phase: SPY_PHASE.VOTE,
        voteStartedAt: now,
        voteStatus: emptyVoteStatus(),
        speakTurnStartedAt: 0
      };
    }
    function publicSpyGame(spyGame, assignments) {
      if (!spyGame) return null;
      const phase = spyGame.phase;
      const voteStatus = spyGame.voteStatus || {};
      const aliveCount = (spyGame.players || []).filter((p) => p && p.alive !== false && p.leftRoom !== true).length;
      const votedCount = (voteStatus.votedPlayerIndexes || []).length;
      const revealWords = phase === SPY_PHASE.SETTLE;
      const base = {
        phase,
        spyCount: spyGame.spyCount,
        round: spyGame.round,
        wordPairId: spyGame.wordPairId || null,
        civilianWord: revealWords ? spyGame.civilianWord : null,
        civilianBlurb: revealWords ? spyGame.civilianBlurb : null,
        spyWord: revealWords ? spyGame.spyWord : null,
        spyBlurb: revealWords ? spyGame.spyBlurb : null,
        players: (spyGame.players || []).filter((p) => p && p.leftRoom !== true).map((p) => ({
          playerIndex: p.playerIndex,
          name: p.name,
          avatarUrl: p.avatarUrl || null,
          avatarIndex: p.avatarIndex != null ? p.avatarIndex : null,
          alive: p.alive !== false,
          leftRoom: p.leftRoom === true
        })),
        speakOrder: spyGame.speakOrder || [],
        currentSpeakIndex: spyGame.currentSpeakIndex != null ? spyGame.currentSpeakIndex : 0,
        speakRoundStartedAt: spyGame.speakRoundStartedAt || 0,
        speakTurnStartedAt: spyGame.speakTurnStartedAt || 0,
        voteStartedAt: spyGame.voteStartedAt || 0,
        speakRoundMs: spyGame.speakRoundMs || SPEAK_ROUND_MS,
        speakTurnMs: spyGame.speakTurnMs || SPEAK_TURN_MS,
        voteDeadlineMs: spyGame.voteDeadlineMs || VOTE_ROUND_MS,
        voteStatus: {
          votedPlayerIndexes: Array.isArray(voteStatus.votedPlayerIndexes) ? voteStatus.votedPlayerIndexes : [],
          abstainPlayerIndexes: [],
          votedCount,
          totalVoters: aliveCount
        },
        lastResult: spyGame.lastResult || null,
        winnerSide: spyGame.winnerSide || null,
        tieBreak: spyGame.tieBreak === true
      };
      if (revealWords) {
        const reveal = buildRevealList(spyGame, assignments || {});
        base.reveal = reveal;
        if (base.lastResult) {
          base.lastResult = { ...base.lastResult, reveal };
        }
      }
      return base;
    }
    function assertRevision(room, expectedRevision) {
      if (expectedRevision != null && Number(expectedRevision) !== Number(room.revision)) {
        return fail(ERR.REVISION_CONFLICT, null, { currentRevision: room.revision });
      }
      return null;
    }
    function actorSeatNo(room, actorUserId) {
      const seat = Object.keys(room.seatMap || {}).find(
        (s) => String(room.seatMap[s]) === String(actorUserId)
      );
      return seat != null ? Number(seat) : null;
    }
    function patchSpyRoom(room, spyGame, page, ts, extras) {
      const domainRevisions = {
        ...room.domainRevisions || {},
        session: (room.domainRevisions && room.domainRevisions.session || 0) + 1
      };
      const order = spyGame.speakOrder || [];
      const cur = spyGame.currentSpeakIndex != null ? Number(spyGame.currentSpeakIndex) : 0;
      const activeSeatNo = cur < order.length ? Number(order[cur]) : null;
      return {
        ...room,
        ...extras || {},
        selectedModeId: room.selectedModeId || "spy",
        currentPage: page,
        brainstormProgressPage: page,
        spyGame,
        domainRevisions,
        revision: room.revision + 1,
        updatedAt: ts,
        workflow: {
          mode: "SPY",
          step: `SPY_${String(spyGame.phase || "INTRO").toUpperCase()}`,
          roundNo: spyGame.round || 1,
          turnId: `spy_r${spyGame.round || 1}_s${activeSeatNo != null ? activeSeatNo : 0}`,
          activeSeatNo,
          deadlineAt: spyGame.phase === SPY_PHASE.SPEAK && spyGame.speakTurnStartedAt ? spyGame.speakTurnStartedAt + (spyGame.speakTurnMs || SPEAK_TURN_MS) : null
        }
      };
    }
    function okSpy(commandId, next, effects) {
      const assignments = next.spyAssignments || assignmentsMap(next);
      return okResult({
        commandId,
        appliedRevision: next.revision,
        changedDomains: ["session"],
        room: next,
        effects: {
          legacyPage: next.currentPage,
          spyGame: publicSpyGame(next.spyGame, assignments),
          ...effects || {}
        }
      });
    }
    function resolveVote(room, spyGame, ts, random) {
      const assignments = assignmentsMap(room);
      const tally = spyGame.voteStatus && spyGame.voteStatus.tally || {};
      let maxVotes = 0;
      let topIndexes = [];
      Object.keys(tally).forEach((key) => {
        const count = Number(tally[key]) || 0;
        const idx = Number(key);
        if (count > maxVotes) {
          maxVotes = count;
          topIndexes = [idx];
        } else if (count === maxVotes && count > 0) {
          topIndexes.push(idx);
        }
      });
      const publicTallies = { ...tally };
      if (maxVotes > 0 && topIndexes.length > 1) {
        const tiedOrder = shuffle(topIndexes.slice(), random);
        let nextGame2 = {
          ...spyGame,
          lastResult: {
            eliminatedIndex: null,
            eliminatedRole: null,
            eliminatedName: "",
            maxVotes,
            tied: true,
            tiedIndexes: topIndexes,
            tallies: publicTallies,
            winnerSide: null
          },
          tieBreak: true,
          winnerSide: null
        };
        nextGame2 = beginSpeakPhase(nextGame2, tiedOrder, ts);
        const page2 = pageForPhase(SPY_PHASE.SPEAK);
        const next2 = patchSpyRoom(room, nextGame2, page2, ts);
        return okSpy(null, next2, { tied: true, settled: false });
      }
      let eliminatedIndex = null;
      let eliminatedRole = null;
      let eliminatedName = "";
      let nextGame = { ...spyGame };
      if (maxVotes > 0 && topIndexes.length === 1) {
        eliminatedIndex = topIndexes[0];
        const card = assignments[String(eliminatedIndex)];
        eliminatedRole = card ? card.role : null;
        const snap = (nextGame.players || []).find((p) => samePlayerIndex(p.playerIndex, eliminatedIndex));
        eliminatedName = snap && snap.name || card && card.name || `\u73A9\u5BB6${eliminatedIndex}`;
        nextGame.players = (nextGame.players || []).map((p) => samePlayerIndex(p.playerIndex, eliminatedIndex) ? { ...p, alive: false } : p);
      }
      const rolePlayers = (nextGame.players || []).map((p) => {
        const card = assignments[String(p.playerIndex)] || {};
        return { role: card.role || "civilian", alive: p.alive !== false };
      });
      const winnerSide = resolveWinnerSide(rolePlayers);
      nextGame.lastResult = {
        eliminatedIndex,
        eliminatedRole,
        eliminatedName,
        maxVotes,
        tied: false,
        tallies: publicTallies,
        winnerSide
      };
      nextGame.winnerSide = winnerSide;
      nextGame.tieBreak = false;
      if (winnerSide) {
        nextGame.phase = SPY_PHASE.SETTLE;
        const reveal = buildRevealList(nextGame, assignments);
        nextGame.lastResult = { ...nextGame.lastResult, reveal };
        const page2 = pageForPhase(SPY_PHASE.SETTLE);
        const next2 = patchSpyRoom(room, nextGame, page2, ts);
        return okSpy(null, next2, { settled: true });
      }
      nextGame.phase = SPY_PHASE.RESULT;
      const page = pageForPhase(SPY_PHASE.RESULT);
      const next = patchSpyRoom(room, nextGame, page, ts);
      return okSpy(null, next, { settled: false });
    }
    function executeSpyCommand(ctx) {
      const {
        room,
        envelope,
        actorUserId,
        ts,
        wordPairPicker,
        random
      } = ctx;
      const { type, commandId, expectedRevision, payload } = envelope;
      const seatNo = actorSeatNo(room, actorUserId);
      const isHost = String(room.hostUserId) === String(actorUserId);
      if (type === COMMAND_TYPES.SPY_GET_MY_CARD) {
        if (!seatNo && !isHost) return fail(ERR.NOT_MEMBER);
        const secrets = room.secretsByUserId || {};
        const secret = secrets[actorUserId];
        if (!secret) return fail(ERR.NO_CARD);
        const speakOrder = room.spyGame && room.spyGame.speakOrder || [];
        const playerIndex = secret.playerIndex != null ? Number(secret.playerIndex) : Number(seatNo);
        const speakOrderRank = speakOrder.findIndex((idx) => Number(idx) === playerIndex) + 1;
        return okResult({
          commandId,
          appliedRevision: room.revision,
          changedDomains: [],
          room,
          effects: {
            readOnly: true,
            card: {
              playerIndex,
              role: secret.role,
              word: secret.word,
              blurb: secret.blurb,
              speakOrderRank: speakOrderRank > 0 ? speakOrderRank : null,
              speakOrderTotal: speakOrder.length
            },
            spyGame: publicSpyGame(room.spyGame, assignmentsMap(room))
          }
        });
      }
      if (type === COMMAND_TYPES.SPY_START_ASSIGN) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const revErr = assertRevision(room, expectedRevision);
        if (revErr) return revErr;
        const players = listPlayableMembers(room);
        if (players.length < MIN_PLAYERS) {
          return fail(ERR.NOT_ENOUGH_PLAYERS, `\u81F3\u5C11\u9700\u8981 ${MIN_PLAYERS} \u540D\u73A9\u5BB6`);
        }
        const phase = room.spyGame && room.spyGame.phase;
        if (phase && phase !== SPY_PHASE.INTRO && phase !== SPY_PHASE.SETTLE) {
          return fail(ERR.GAME_IN_PROGRESS);
        }
        const pair = typeof wordPairPicker === "function" ? wordPairPicker() : pickDefaultWordPair(random);
        if (!pair || !pair.civilianWord || !pair.spyWord) {
          return fail(ERR.NO_WORD_PAIR);
        }
        const spyCount = getDefaultSpyCount(players.length);
        const shuffled = shuffle(players, random);
        const secretsByUserId = {};
        const assignmentsBySeat = {};
        shuffled.forEach((m, index) => {
          const isSpy = index < spyCount;
          const row = {
            playerIndex: m.playerIndex,
            userId: m.userId,
            role: isSpy ? "spy" : "civilian",
            word: isSpy ? pair.spyWord : pair.civilianWord,
            blurb: isSpy ? pair.spyBlurb || "" : pair.civilianBlurb || "",
            name: m.nickName
          };
          secretsByUserId[m.userId] = row;
          assignmentsBySeat[String(m.playerIndex)] = row;
        });
        const speakOrder = shuffle(players.map((m) => m.playerIndex), random);
        const playerSnaps = players.map((m) => ({
          playerIndex: m.playerIndex,
          name: m.nickName,
          avatarUrl: m.avatarUrl,
          avatarIndex: m.avatarIndex,
          alive: true
        }));
        let spyGame = {
          phase: SPY_PHASE.SPEAK,
          spyCount,
          round: 1,
          wordPairId: pair.id || null,
          civilianWord: pair.civilianWord,
          civilianBlurb: pair.civilianBlurb || "",
          spyWord: pair.spyWord,
          spyBlurb: pair.spyBlurb || "",
          players: playerSnaps,
          speakOrder,
          currentSpeakIndex: 0,
          speakRoundStartedAt: 0,
          speakTurnStartedAt: 0,
          voteStartedAt: 0,
          speakRoundMs: SPEAK_ROUND_MS,
          speakTurnMs: SPEAK_TURN_MS,
          voteDeadlineMs: VOTE_ROUND_MS,
          voteStatus: emptyVoteStatus(),
          lastResult: null,
          winnerSide: null,
          tieBreak: false
        };
        spyGame = beginSpeakPhase(spyGame, speakOrder, ts);
        const page = pageForPhase(SPY_PHASE.SPEAK);
        const next = patchSpyRoom(room, spyGame, page, ts, {
          spyAssignments: assignmentsBySeat,
          secretsByUserId,
          selectedModeId: "spy"
        });
        const result = okSpy(commandId, next, {
          spyStarted: true,
          secretsUpsert: true,
          combinedStartSpeak: true,
          payloadNote: payload || null
        });
        result.commandId = commandId;
        return result;
      }
      if (type === COMMAND_TYPES.SPY_START_SPEAK) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const revErr = assertRevision(room, expectedRevision);
        if (revErr) return revErr;
        if (room.spyGame && room.spyGame.phase === SPY_PHASE.SPEAK && payload && payload.forceVote) {
          let spyGame = { ...room.spyGame };
          const order = spyGame.speakOrder || [];
          spyGame.currentSpeakIndex = order.length;
          spyGame = beginVotePhase(spyGame, ts);
          spyGame.tieBreak = false;
          const page = pageForPhase(SPY_PHASE.VOTE);
          const next = patchSpyRoom(room, spyGame, page, ts);
          const result = okSpy(commandId, next, { autoVote: true, finished: true });
          result.commandId = commandId;
          return result;
        }
        if (room.spyGame && room.spyGame.phase === SPY_PHASE.SPEAK) {
          return okResult({
            commandId,
            appliedRevision: room.revision,
            changedDomains: [],
            room,
            effects: {
              readOnly: true,
              already: true,
              spyGame: publicSpyGame(room.spyGame, assignmentsMap(room)),
              legacyPage: pageForPhase(SPY_PHASE.SPEAK)
            }
          });
        }
        return fail(ERR.INVALID_TRANSITION, "\u8BF7\u5148\u5206\u724C\u5F00\u5C40");
      }
      if (type === COMMAND_TYPES.SPY_ADVANCE_SPEAKER) {
        const revErr = assertRevision(room, expectedRevision);
        if (revErr) return revErr;
        let spyGame = room.spyGame ? { ...room.spyGame } : null;
        if (!spyGame || spyGame.phase !== SPY_PHASE.SPEAK) {
          return fail(ERR.INVALID_TRANSITION, "\u5F53\u524D\u4E0D\u5728\u53D1\u8A00\u9636\u6BB5");
        }
        if (!seatNo && !isHost) return fail(ERR.NOT_MEMBER);
        const order = spyGame.speakOrder || [];
        const curIdx = spyGame.currentSpeakIndex != null ? Number(spyGame.currentSpeakIndex) : 0;
        const currentPlayerIndex = curIdx < order.length ? order[curIdx] : null;
        const isCurrentSpeaker = currentPlayerIndex != null && samePlayerIndex(seatNo, currentPlayerIndex);
        if (payload && payload.forceVote) {
          if (!isHost) return fail(ERR.HOST_REQUIRED);
          spyGame.currentSpeakIndex = order.length;
          spyGame = beginVotePhase(spyGame, ts);
          spyGame.tieBreak = false;
          const page = pageForPhase(SPY_PHASE.VOTE);
          const next2 = patchSpyRoom(room, spyGame, page, ts);
          const result2 = okSpy(commandId, next2, { finished: true, autoVote: true });
          result2.commandId = commandId;
          return result2;
        }
        if (!isCurrentSpeaker) {
          return fail(ERR.INVALID_TRANSITION, "\u4EC5\u5F53\u524D\u53D1\u8A00\u8005\u53EF\u7ED3\u675F\u53D1\u8A00");
        }
        const nextIdx = findSpeakIndex(order, spyGame.players, curIdx + 1);
        if (nextIdx >= order.length) {
          spyGame.currentSpeakIndex = order.length;
          spyGame = beginVotePhase(spyGame, ts);
          spyGame.tieBreak = false;
          const page = pageForPhase(SPY_PHASE.VOTE);
          const next2 = patchSpyRoom(room, spyGame, page, ts);
          const result2 = okSpy(commandId, next2, { finished: true, autoVote: true });
          result2.commandId = commandId;
          return result2;
        }
        spyGame.currentSpeakIndex = nextIdx;
        spyGame.speakTurnStartedAt = ts;
        spyGame.speakTurnMs = spyGame.speakTurnMs || SPEAK_TURN_MS;
        const next = patchSpyRoom(room, spyGame, pageForPhase(SPY_PHASE.SPEAK), ts);
        const result = okSpy(commandId, next, { finished: false });
        result.commandId = commandId;
        return result;
      }
      if (type === COMMAND_TYPES.SPY_SUBMIT_VOTE) {
        if (!seatNo) return fail(ERR.NOT_MEMBER);
        let spyGame = room.spyGame ? { ...room.spyGame } : null;
        if (!spyGame || spyGame.phase !== SPY_PHASE.VOTE) {
          return fail(ERR.INVALID_TRANSITION, "\u5F53\u524D\u4E0D\u5728\u6295\u7968\u9636\u6BB5");
        }
        const mySnap = (spyGame.players || []).find((p) => samePlayerIndex(p.playerIndex, seatNo));
        if (!mySnap || mySnap.alive === false) {
          return fail(ERR.INVALID_TRANSITION, "\u5DF2\u51FA\u5C40\u65E0\u6CD5\u6295\u7968");
        }
        const voteStatus = {
          votedPlayerIndexes: [...spyGame.voteStatus && spyGame.voteStatus.votedPlayerIndexes || []],
          abstainPlayerIndexes: [],
          tally: { ...spyGame.voteStatus && spyGame.voteStatus.tally || {} },
          ballots: { ...spyGame.voteStatus && spyGame.voteStatus.ballots || {} }
        };
        if (indexIncludes(voteStatus.votedPlayerIndexes, seatNo)) {
          return fail(ERR.ALREADY_VOTED, "\u5DF2\u6295\u7968\uFF0C\u4E0D\u53EF\u4FEE\u6539");
        }
        const targetPlayerIndex = Number(payload && payload.targetPlayerIndex);
        if (!targetPlayerIndex || samePlayerIndex(targetPlayerIndex, seatNo)) {
          return fail(ERR.INVALID_ARGUMENT, "\u8BF7\u9009\u62E9\u4E00\u540D\u5176\u4ED6\u73A9\u5BB6");
        }
        const target = (spyGame.players || []).find((p) => samePlayerIndex(p.playerIndex, targetPlayerIndex));
        if (!target || target.alive === false) {
          return fail(ERR.INVALID_ARGUMENT, "\u76EE\u6807\u4E0D\u53EF\u6295\u7968");
        }
        const key = String(targetPlayerIndex);
        voteStatus.tally[key] = (Number(voteStatus.tally[key]) || 0) + 1;
        voteStatus.ballots[String(seatNo)] = { abstain: false, targetPlayerIndex };
        voteStatus.votedPlayerIndexes.push(seatNo);
        spyGame.voteStatus = voteStatus;
        const aliveVoters = (spyGame.players || []).filter((p) => p && p.alive !== false && p.leftRoom !== true);
        const allVoted = aliveVoters.every((p) => indexIncludes(voteStatus.votedPlayerIndexes, p.playerIndex));
        if (allVoted) {
          const resolved = resolveVote(room, spyGame, ts, random);
          resolved.commandId = commandId;
          return resolved;
        }
        const next = patchSpyRoom(room, spyGame, pageForPhase(SPY_PHASE.VOTE), ts);
        const result = okSpy(commandId, next, {});
        result.commandId = commandId;
        return result;
      }
      if (type === COMMAND_TYPES.SPY_CONFIRM_RESULT) {
        if (!seatNo && !isHost) return fail(ERR.NOT_MEMBER);
        return okResult({
          commandId,
          appliedRevision: room.revision,
          changedDomains: [],
          room,
          effects: {
            readOnly: true,
            deprecated: true,
            spyGame: publicSpyGame(room.spyGame, assignmentsMap(room)),
            legacyPage: room.currentPage || pageForPhase(room.spyGame && room.spyGame.phase)
          }
        });
      }
      if (type === COMMAND_TYPES.SPY_NEXT_ROUND || type === COMMAND_TYPES.SPY_CONTINUE) {
        if (!seatNo && !isHost) return fail(ERR.NOT_MEMBER);
        const revErr = assertRevision(room, expectedRevision);
        if (revErr) return revErr;
        let spyGame = room.spyGame ? { ...room.spyGame } : null;
        if (!spyGame) return fail(ERR.INVALID_TRANSITION, "\u5F53\u524D\u65E0\u6CD5\u8FDB\u5165\u4E0B\u4E00\u8F6E");
        if (spyGame.phase === SPY_PHASE.SPEAK && !spyGame.tieBreak) {
          return okResult({
            commandId,
            appliedRevision: room.revision,
            changedDomains: [],
            room,
            effects: {
              readOnly: true,
              already: true,
              spyGame: publicSpyGame(spyGame, assignmentsMap(room))
            }
          });
        }
        if (spyGame.phase !== SPY_PHASE.RESULT && spyGame.phase !== SPY_PHASE.NEXT_ROUND) {
          return fail(ERR.INVALID_TRANSITION, "\u5F53\u524D\u65E0\u6CD5\u8FDB\u5165\u4E0B\u4E00\u8F6E");
        }
        const alive = (spyGame.players || []).filter((p) => p.alive !== false && p.leftRoom !== true).map((p) => Number(p.playerIndex));
        if (alive.length < 2) {
          return fail(ERR.INVALID_TRANSITION, "\u5B58\u6D3B\u4EBA\u6570\u4E0D\u8DB3");
        }
        let speakOrder = shuffle(alive, random);
        const eliminated = spyGame.lastResult && spyGame.lastResult.eliminatedIndex;
        if (eliminated != null) {
          const oldOrder = spyGame.speakOrder || [];
          const elimPos = oldOrder.findIndex((idx) => samePlayerIndex(idx, eliminated));
          if (elimPos >= 0) {
            const aliveSet = new Set(alive);
            const rotated = [];
            for (let i = 1; i <= oldOrder.length; i += 1) {
              const idx = Number(oldOrder[(elimPos + i) % oldOrder.length]);
              if (aliveSet.has(idx)) rotated.push(idx);
            }
            if (rotated.length) speakOrder = rotated;
          }
        }
        spyGame.round = (spyGame.round || 1) + 1;
        spyGame.tieBreak = false;
        spyGame.winnerSide = null;
        spyGame = beginSpeakPhase(spyGame, speakOrder, ts);
        const page = pageForPhase(SPY_PHASE.SPEAK);
        const next = patchSpyRoom(room, spyGame, page, ts);
        const result = okSpy(commandId, next, {});
        result.commandId = commandId;
        return result;
      }
      if (type === COMMAND_TYPES.SPY_RESTART) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const revErr = assertRevision(room, expectedRevision);
        if (revErr) return revErr;
        const page = pageForPhase(SPY_PHASE.INTRO);
        const domainRevisions = {
          ...room.domainRevisions || {},
          session: (room.domainRevisions && room.domainRevisions.session || 0) + 1
        };
        const next = {
          ...room,
          currentPage: page,
          brainstormProgressPage: page,
          spyGame: null,
          spyAssignments: null,
          secretsByUserId: null,
          workflow: null,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["session"],
          room: next,
          effects: {
            legacyPage: page,
            spyGame: null,
            secretsClear: true,
            restarted: true
          }
        });
      }
      return fail(ERR.INVALID_ARGUMENT, `\u672A\u5B9E\u73B0\u7684 Spy \u547D\u4EE4: ${type}`);
    }
    module2.exports = {
      SPY_PHASE,
      SPY_PAGE,
      MIN_PLAYERS,
      executeSpyCommand,
      publicSpyGame,
      pageForPhase,
      getDefaultSpyCount,
      resolveWinnerSide,
      DEFAULT_WORD_PAIRS
    };
  }
});

// packages/room-domain/index.js
var require_room_domain = __commonJS({
  "packages/room-domain/index.js"(exports2, module2) {
    "use strict";
    var {
      PROTOCOL_VERSION,
      SCHEMA_VERSION,
      MAX_SEATS,
      LIFECYCLE,
      COMMAND_TYPES,
      ERR,
      fail,
      okResult,
      emptyDomainRevisions,
      isNonEmptyString
    } = require_room_contracts();
    var { executeSpyCommand } = require_spy();
    var AVATAR_COLORS = [
      "#5EC159",
      "#4A90E2",
      "#E24A4A",
      "#E2B84A",
      "#9B59B6",
      "#1ABC9C",
      "#E67E22",
      "#3498DB"
    ];
    function allocateSeatNo(seatMap) {
      const used = new Set(
        Object.keys(seatMap || {}).map((k) => parseInt(k, 10)).filter((n) => Number.isFinite(n))
      );
      for (let seat = 1; seat <= MAX_SEATS; seat += 1) {
        if (!used.has(seat)) return seat;
      }
      return null;
    }
    function pickAvatarColor(seatMap, membersByUserId) {
      const used = [];
      Object.values(seatMap || {}).forEach((userId) => {
        const m = membersByUserId[userId];
        if (m && m.avatarColor) used.push(m.avatarColor);
      });
      const available = AVATAR_COLORS.filter((c) => !used.includes(c));
      return available.length ? available[0] : AVATAR_COLORS[0];
    }
    function buildCapabilities(room, actorUserId) {
      const seatNo = findSeatNo(room.seatMap, actorUserId);
      const isHost = room.hostUserId && String(room.hostUserId) === String(actorUserId);
      const isMember = !!(seatNo || isHost);
      const inLobby = room.lifecycle === LIFECYCLE.LOBBY;
      return {
        joinRoom: {
          allowed: room.lifecycle !== LIFECYCLE.DISSOLVED && memberCount(room.seatMap) < MAX_SEATS,
          reason: room.lifecycle === LIFECYCLE.DISSOLVED ? "ROOM_DISSOLVED" : memberCount(room.seatMap) >= MAX_SEATS ? "ROOM_FULL" : null
        },
        leaveRoom: {
          allowed: isMember && !isHost,
          reason: !isMember ? "NOT_MEMBER" : isHost ? "HOST_CANNOT_LEAVE" : null
        },
        reorderSeats: {
          allowed: isHost && inLobby,
          reason: !isHost ? "HOST_ONLY" : !inLobby ? "INVALID_TRANSITION" : null
        },
        dissolveRoom: {
          allowed: isHost,
          reason: isHost ? null : "HOST_ONLY"
        },
        submitScore: {
          allowed: isMember && !(room.workflow && room.workflow.activeSeatNo != null && Number(seatNo) === Number(room.workflow.activeSeatNo)),
          reason: !isMember ? "NOT_MEMBER" : room.workflow && Number(seatNo) === Number(room.workflow.activeSeatNo) ? "SELF_SCORE" : null
        },
        startStatement: {
          allowed: isHost && room.progress && room.progress.requiredScoreCount > 0 && room.progress.scoredCount >= room.progress.requiredScoreCount,
          reason: !isHost ? "HOST_ONLY" : "SCORES_INCOMPLETE"
        }
      };
    }
    function buildHead(room, actorUserId) {
      const seatNo = findSeatNo(room.seatMap, actorUserId);
      const isHost = room.hostUserId && String(room.hostUserId) === String(actorUserId);
      return {
        protocolVersion: room.protocolVersion || PROTOCOL_VERSION,
        roomId: room.roomId,
        schemaVersion: room.schemaVersion || SCHEMA_VERSION,
        revision: room.revision,
        lifecycle: room.lifecycle,
        activeSessionId: room.activeSessionId || null,
        workflow: room.workflow || null,
        domainRevisions: room.domainRevisions || emptyDomainRevisions(),
        progress: room.progress || {
          scoredCount: 0,
          requiredScoreCount: 0,
          votedCount: 0,
          requiredVoteCount: 0
        },
        actor: {
          role: isHost ? "HOST" : seatNo ? "PLAYER" : "NONE",
          seatNo: seatNo || null
        },
        capabilities: buildCapabilities(room, actorUserId),
        serverTime: Date.now()
      };
    }
    function projectMembersDomain(room, actorUserId) {
      const list = [];
      const seatMap = room.seatMap || {};
      Object.keys(seatMap).map((k) => parseInt(k, 10)).filter((n) => Number.isFinite(n)).sort((a, b) => a - b).forEach((seatNo) => {
        const userId = seatMap[String(seatNo)];
        const m = room.membersByUserId && room.membersByUserId[userId] || {};
        list.push({
          seatNo,
          nickName: m.nickName || `\u73A9\u5BB6${seatNo}`,
          avatarColor: m.avatarColor || "#5EC159",
          avatarUrl: m.avatarUrl || null,
          avatarIndex: m.avatarIndex != null ? m.avatarIndex : null,
          role: m.role === "HOST" || seatNo === 1 ? "HOST" : "PLAYER",
          isMe: String(userId) === String(actorUserId),
          online: m.online !== false
          // 不返回 userId / openid
        });
      });
      return list;
    }
    function projectSnapshot(room, options) {
      const actorUserId = options && options.actorUserId;
      const requested = options && options.domains && options.domains.length ? options.domains : ["members"];
      const clientRevs = options && options.clientDomainRevisions || {};
      const serverRevs = room.domainRevisions || emptyDomainRevisions();
      const extra = options && options.extraDomainData || {};
      const domains = {};
      requested.forEach((name) => {
        const serverRev = serverRevs[name] != null ? serverRevs[name] : 0;
        const clientRev = clientRevs[name] != null ? clientRevs[name] : -1;
        if (clientRev >= serverRev && clientRev >= 0) {
          return;
        }
        let data = null;
        if (name === "members") {
          data = projectMembersDomain(room, actorUserId);
        } else if (Object.prototype.hasOwnProperty.call(extra, name)) {
          data = extra[name];
        } else {
          data = name === "scores" || name === "votes" ? {} : [];
        }
        domains[name] = { revision: serverRev, data };
      });
      return {
        roomId: room.roomId,
        revision: room.revision,
        domains,
        serverTime: Date.now()
      };
    }
    function authorizeRoomRead(room, actorUserId) {
      if (!isNonEmptyString(actorUserId)) {
        return fail(ERR.UNAUTHENTICATED);
      }
      if (!room) {
        return fail(ERR.ROOM_NOT_FOUND);
      }
      if (room.lifecycle === LIFECYCLE.DISSOLVED || room.status === "DISSOLVED") {
        return fail(ERR.ROOM_DISSOLVED);
      }
      const seatNo = findSeatNo(room.seatMap, actorUserId);
      const isHost = room.hostUserId && String(room.hostUserId) === String(actorUserId);
      if (!seatNo && !isHost) {
        return fail(ERR.NOT_MEMBER);
      }
      return okResult({ room });
    }
    function findSeatNo(seatMap, userId) {
      if (!userId || !seatMap) return null;
      const entries = Object.entries(seatMap);
      for (let i = 0; i < entries.length; i += 1) {
        if (String(entries[i][1]) === String(userId)) {
          return parseInt(entries[i][0], 10);
        }
      }
      return null;
    }
    function memberCount(seatMap) {
      return Object.keys(seatMap || {}).length;
    }
    function assertActor(actorUserId) {
      if (!isNonEmptyString(actorUserId)) {
        return fail(ERR.UNAUTHENTICATED);
      }
      return null;
    }
    function createRoomAggregate({ roomId, actorUserId, payload, now }) {
      const nickName = isNonEmptyString(payload.nickName) ? String(payload.nickName).trim() : "\u73A9\u5BB61";
      const avatarUrl = payload.avatarUrl || null;
      const avatarColor = pickAvatarColor({}, {});
      const member = {
        userId: actorUserId,
        seatNo: 1,
        role: "HOST",
        nickName,
        avatarUrl,
        avatarColor,
        avatarIndex: avatarUrl ? null : 0,
        joinedAt: now
      };
      return {
        roomId,
        schemaVersion: SCHEMA_VERSION,
        protocolVersion: PROTOCOL_VERSION,
        lifecycle: LIFECYCLE.LOBBY,
        // 兼容旧字段
        status: "CREATED",
        hostUserId: actorUserId,
        creatorId: actorUserId,
        seatMap: { "1": actorUserId },
        activeSessionId: null,
        revision: 1,
        workflow: null,
        domainRevisions: { ...emptyDomainRevisions(), members: 1 },
        progress: {
          scoredCount: 0,
          requiredScoreCount: 0,
          votedCount: 0,
          requiredVoteCount: 0
        },
        workshopName: isNonEmptyString(payload.workshopName) ? String(payload.workshopName).trim() : "\u8111\u66B4\u5DE5\u4F5C\u574A",
        membersByUserId: { [actorUserId]: member },
        createdAt: now,
        updatedAt: now
      };
    }
    function executeCommand({
      room,
      envelope,
      actorUserId,
      roomIdFactory,
      now,
      wordPairPicker,
      random
    }) {
      const authErr = assertActor(actorUserId);
      if (authErr) return authErr;
      const ts = now || Date.now();
      const { type, payload, expectedRevision, commandId, roomId } = envelope;
      if (type === COMMAND_TYPES.CREATE_ROOM) {
        if (room) {
          return fail(ERR.INVALID_ARGUMENT, "\u623F\u95F4\u5DF2\u5B58\u5728");
        }
        const newRoomId = roomIdFactory ? roomIdFactory() : null;
        if (!isNonEmptyString(newRoomId)) {
          return fail(ERR.INTERNAL_ERROR, "\u65E0\u6CD5\u751F\u6210 roomId");
        }
        const next = createRoomAggregate({
          roomId: newRoomId,
          actorUserId,
          payload: payload || {},
          now: ts
        });
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { created: true }
        });
      }
      if (!room) {
        return fail(ERR.ROOM_NOT_FOUND);
      }
      if (room.lifecycle === LIFECYCLE.DISSOLVED || room.status === "DISSOLVED") {
        return fail(ERR.ROOM_DISSOLVED);
      }
      if (type === COMMAND_TYPES.JOIN_ROOM) {
        const existingSeat = findSeatNo(room.seatMap, actorUserId);
        if (existingSeat) {
          const membersByUserId2 = { ...room.membersByUserId };
          const prev = membersByUserId2[actorUserId] || {};
          const nextMember = { ...prev };
          if (isNonEmptyString(payload.nickName)) {
            nextMember.nickName = String(payload.nickName).trim();
          }
          if (payload.avatarUrl !== void 0) {
            nextMember.avatarUrl = payload.avatarUrl || null;
          }
          membersByUserId2[actorUserId] = nextMember;
          const next2 = {
            ...room,
            membersByUserId: membersByUserId2,
            updatedAt: ts
          };
          return okResult({
            commandId,
            appliedRevision: room.revision,
            changedDomains: [],
            room: next2,
            head: buildHead(next2, actorUserId),
            effects: { alreadyMember: true, seatNo: existingSeat }
          });
        }
        if (memberCount(room.seatMap) >= MAX_SEATS) {
          return fail(ERR.ROOM_FULL);
        }
        if (room.lifecycle !== LIFECYCLE.LOBBY && room.lifecycle !== LIFECYCLE.ACTIVE) {
          return fail(ERR.INVALID_TRANSITION);
        }
        const seatNo = allocateSeatNo(room.seatMap);
        if (seatNo == null) return fail(ERR.ROOM_FULL);
        const nickName = isNonEmptyString(payload.nickName) ? String(payload.nickName).trim() : `\u73A9\u5BB6${seatNo}`;
        const avatarUrl = payload.avatarUrl || null;
        const avatarColor = pickAvatarColor(room.seatMap, room.membersByUserId || {});
        const member = {
          userId: actorUserId,
          seatNo,
          role: "PLAYER",
          nickName,
          avatarUrl,
          avatarColor,
          avatarIndex: avatarUrl ? null : Math.min(seatNo - 1, 8),
          joinedAt: ts
        };
        const seatMap = { ...room.seatMap, [String(seatNo)]: actorUserId };
        const membersByUserId = { ...room.membersByUserId || {}, [actorUserId]: member };
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          seatMap,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { joined: true, seatNo }
        });
      }
      {
        const factTypes = [
          COMMAND_TYPES.SUBMIT_SCORE,
          COMMAND_TYPES.POST_MESSAGE,
          COMMAND_TYPES.SUBMIT_CLOSING_VOTE,
          COMMAND_TYPES.APPEND_ARTIFACT
        ];
        if (factTypes.includes(type)) {
          const actorSeat2 = findSeatNo(room.seatMap, actorUserId);
          const isHost2 = String(room.hostUserId) === String(actorUserId);
          if (!actorSeat2 && !isHost2) {
            return fail(ERR.NOT_MEMBER);
          }
          if (type === COMMAND_TYPES.SUBMIT_SCORE) {
            const score = parseInt(payload.score, 10);
            if (!Number.isFinite(score) || score < 0 || score > 5) {
              return fail(ERR.INVALID_ARGUMENT, "score \u9700\u4E3A 0\uFF5E5");
            }
            const activeSeatNo = room.workflow && room.workflow.activeSeatNo != null ? Number(room.workflow.activeSeatNo) : payload.activeSeatNo != null ? Number(payload.activeSeatNo) : null;
            if (activeSeatNo != null && Number(actorSeat2) === Number(activeSeatNo)) {
              return fail(ERR.SELF_SCORE);
            }
            const turnId = room.workflow && room.workflow.turnId || payload.turnId || `turn_r${room.workflow && room.workflow.roundNo || 1}_s${activeSeatNo || 0}`;
            const scores = { ...room.scoresByKey || {} };
            const key = `${turnId}:${actorUserId}`;
            scores[key] = {
              turnId,
              scorerUserId: actorUserId,
              activeSeatNo,
              score,
              updatedAt: ts
            };
            const required = Math.max(0, memberCount(room.seatMap) - 1);
            const scoredUserIds = /* @__PURE__ */ new Set();
            Object.keys(scores).forEach((k) => {
              const row = scores[k];
              if (row && row.turnId === turnId) scoredUserIds.add(row.scorerUserId);
            });
            const progress = {
              scoredCount: scoredUserIds.size,
              requiredScoreCount: required,
              votedCount: room.progress && room.progress.votedCount || 0,
              requiredVoteCount: room.progress && room.progress.requiredVoteCount || 0,
              turnId
            };
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              scores: (room.domainRevisions && room.domainRevisions.scores || 0) + 1
            };
            const next = {
              ...room,
              scoresByKey: scores,
              progress,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["scores"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: {
                scoreUpsert: true,
                scoreKey: key,
                scoredCount: progress.scoredCount,
                totalRequired: required
              }
            });
          }
          if (type === COMMAND_TYPES.POST_MESSAGE) {
            const text = typeof payload.text === "string" ? payload.text.trim() : "";
            if (!text) return fail(ERR.INVALID_ARGUMENT, "\u5185\u5BB9\u4E0D\u80FD\u4E3A\u7A7A");
            if (text.length > 40) return fail(ERR.INVALID_ARGUMENT, "\u6700\u591A 40 \u5B57");
            const messageId = payload.messageId || `msg_${commandId}`;
            const messages = Array.isArray(room.messages) ? room.messages.slice() : [];
            if (!messages.some((m) => m && m.id === messageId)) {
              messages.push({
                id: messageId,
                text,
                at: ts,
                round: payload.round != null ? Number(payload.round) : 0,
                phase: payload.phase === "discussion" ? "discussion" : "play",
                anonKey: payload.anonKey || null
              });
            }
            const trimmed = messages.slice(-40);
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              messages: (room.domainRevisions && room.domainRevisions.messages || 0) + 1
            };
            const next = {
              ...room,
              messages: trimmed,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["messages"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: { messageAppended: true, messageId }
            });
          }
          if (type === COMMAND_TYPES.SUBMIT_CLOSING_VOTE) {
            const vote = String(payload.vote || "");
            if (vote !== "pass" && vote !== "question") {
              return fail(ERR.INVALID_ARGUMENT, "vote \u9700\u4E3A pass \u6216 question");
            }
            const voteSessionId = room.workflow && room.workflow.voteSessionId || payload.voteSessionId || `vote_${room.roomId}`;
            const votes = { ...room.votesByKey || {} };
            const key = `${voteSessionId}:${actorUserId}`;
            if (votes[key]) {
              return fail(ERR.ALREADY_VOTED);
            }
            votes[key] = {
              voteSessionId,
              voterUserId: actorUserId,
              seatNo: actorSeat2,
              vote,
              at: ts
            };
            const required = memberCount(room.seatMap);
            const votedCount = Object.keys(votes).filter((k) => votes[k].voteSessionId === voteSessionId).length;
            const progress = {
              ...room.progress || {},
              votedCount,
              requiredVoteCount: required
            };
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              votes: (room.domainRevisions && room.domainRevisions.votes || 0) + 1
            };
            const next = {
              ...room,
              votesByKey: votes,
              progress,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["votes"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: { voteUpsert: true, voteKey: key, votedCount, totalMembers: required }
            });
          }
          if (type === COMMAND_TYPES.APPEND_ARTIFACT) {
            const operationId = payload.operationId || commandId;
            const artifacts = Array.isArray(room.artifacts) ? room.artifacts.slice() : [];
            if (!artifacts.some((a) => a && a.operationId === operationId)) {
              artifacts.push({
                operationId,
                kind: payload.kind || "text",
                turnId: payload.turnId || null,
                stage: payload.stage || "play",
                body: payload.body || null,
                at: ts
              });
            }
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              artifacts: (room.domainRevisions && room.domainRevisions.artifacts || 0) + 1
            };
            const next = {
              ...room,
              artifacts,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["artifacts"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: { artifactAppended: true, operationId }
            });
          }
        }
      }
      if (String(type).indexOf("SPY_") === 0) {
        const spyResult = executeSpyCommand({
          room,
          envelope,
          actorUserId,
          ts,
          wordPairPicker,
          random
        });
        if (!spyResult.ok) return spyResult;
        return okResult({
          ...spyResult,
          head: spyResult.effects && spyResult.effects.readOnly ? buildHead(room, actorUserId) : buildHead(spyResult.room, actorUserId)
        });
      }
      const actorSeat = findSeatNo(room.seatMap, actorUserId);
      const isHost = String(room.hostUserId) === String(actorUserId);
      if (!actorSeat && !isHost) {
        return fail(ERR.NOT_MEMBER);
      }
      if (expectedRevision == null || Number(expectedRevision) !== Number(room.revision)) {
        return fail(ERR.REVISION_CONFLICT, void 0, {
          latestHead: buildHead(room, actorUserId)
        });
      }
      if (type === COMMAND_TYPES.START_STATEMENT) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const progress = room.progress || {};
        const scored = progress.scoredCount || 0;
        const required = progress.requiredScoreCount || 0;
        if (required <= 0 || scored < required) {
          return fail(ERR.INVALID_TRANSITION, "\u8BC4\u5206\u672A\u5B8C\u6210");
        }
        const workflow = {
          ...room.workflow || {},
          mode: "PARTNER",
          step: "STATEMENT",
          legacyPage: "statement"
        };
        const next = {
          ...room,
          lifecycle: LIFECYCLE.ACTIVE,
          status: "STARTED",
          workflow,
          revision: room.revision + 1,
          domainRevisions: {
            ...room.domainRevisions || emptyDomainRevisions(),
            session: (room.domainRevisions && room.domainRevisions.session || 0) + 1
          },
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["session"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { startedStatement: true, legacyPage: "statement" }
        });
      }
      if (type === COMMAND_TYPES.ADVANCE_TURN) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const seats = Object.keys(room.seatMap || {}).map((k) => parseInt(k, 10)).filter((n) => Number.isFinite(n)).sort((a, b) => a - b);
        if (!seats.length) return fail(ERR.INVALID_TRANSITION, "\u65E0\u6709\u6548\u5E2D\u4F4D");
        const current = room.workflow && room.workflow.activeSeatNo != null ? Number(room.workflow.activeSeatNo) : seats[0];
        const idx = seats.indexOf(current);
        const nextSeat = seats[(idx >= 0 ? idx + 1 : 0) % seats.length];
        const wrapped = idx >= 0 && nextSeat === seats[0] && current === seats[seats.length - 1];
        const roundNo = (room.workflow && room.workflow.roundNo || 1) + (wrapped ? 1 : 0);
        const turnId = `turn_r${roundNo}_s${nextSeat}`;
        const workflow = {
          ...room.workflow || {},
          mode: "PARTNER",
          step: "TURN_ACTIVE",
          activeSeatNo: nextSeat,
          roundNo,
          turnId,
          legacyPage: "gamepage"
        };
        const progress = {
          scoredCount: 0,
          requiredScoreCount: Math.max(0, seats.length - 1),
          votedCount: 0,
          requiredVoteCount: 0,
          turnId
        };
        const next = {
          ...room,
          workflow,
          progress,
          revision: room.revision + 1,
          domainRevisions: {
            ...room.domainRevisions || emptyDomainRevisions(),
            session: (room.domainRevisions && room.domainRevisions.session || 0) + 1,
            scores: (room.domainRevisions && room.domainRevisions.scores || 0) + 1
          },
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["session", "scores"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: {
            advancedTurn: true,
            activeSeatNo: nextSeat,
            roundNo,
            turnId,
            legacyPage: "gamepage"
          }
        });
      }
      if (type === COMMAND_TYPES.LEAVE_ROOM) {
        if (isHost) {
          return fail(ERR.HOST_CANNOT_LEAVE);
        }
        const seatMap = { ...room.seatMap };
        delete seatMap[String(actorSeat)];
        const membersByUserId = { ...room.membersByUserId || {} };
        delete membersByUserId[actorUserId];
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          seatMap,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { left: true, freedSeatNo: actorSeat }
        });
      }
      if (type === COMMAND_TYPES.DISSOLVE_ROOM) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const next = {
          ...room,
          lifecycle: LIFECYCLE.DISSOLVED,
          status: "DISSOLVED",
          seatMap: {},
          membersByUserId: {},
          domainRevisions: {
            ...room.domainRevisions || emptyDomainRevisions(),
            members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
          },
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { dissolved: true }
        });
      }
      if (type === COMMAND_TYPES.REORDER_SEATS) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        if (room.lifecycle !== LIFECYCLE.LOBBY) {
          return fail(ERR.INVALID_TRANSITION, "\u4EC5\u5927\u5385\u53EF\u8C03\u6574\u5E2D\u4F4D");
        }
        const order = Array.isArray(payload.userIdOrder) ? payload.userIdOrder : null;
        if (!order || !order.length) {
          return fail(ERR.INVALID_ARGUMENT, "userIdOrder \u5FC5\u586B");
        }
        const currentIds = Object.values(room.seatMap || {}).map(String).sort();
        const nextIds = order.map(String).sort();
        if (currentIds.length !== nextIds.length || currentIds.join(",") !== nextIds.join(",")) {
          return fail(ERR.INVALID_ARGUMENT, "\u5E2D\u4F4D\u6210\u5458\u96C6\u5408\u5FC5\u987B\u4E00\u81F4");
        }
        if (order.length > MAX_SEATS) {
          return fail(ERR.INVALID_ARGUMENT, "\u5E2D\u4F4D\u8D85\u51FA\u4E0A\u9650");
        }
        const seatMap = {};
        const membersByUserId = { ...room.membersByUserId || {} };
        order.forEach((uid, idx) => {
          const seatNo = idx + 1;
          seatMap[String(seatNo)] = uid;
          if (membersByUserId[uid]) {
            membersByUserId[uid] = {
              ...membersByUserId[uid],
              seatNo,
              role: seatNo === 1 ? "HOST" : "PLAYER"
            };
          }
        });
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          seatMap,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { reordered: true }
        });
      }
      if (type === COMMAND_TYPES.UPDATE_MEMBER_PROFILE) {
        const membersByUserId = { ...room.membersByUserId || {} };
        const prev = membersByUserId[actorUserId];
        if (!prev) return fail(ERR.NOT_MEMBER);
        const nextMember = { ...prev };
        if (isNonEmptyString(payload.nickName)) {
          nextMember.nickName = String(payload.nickName).trim();
        }
        if (payload.avatarUrl !== void 0) {
          nextMember.avatarUrl = payload.avatarUrl || null;
        }
        membersByUserId[actorUserId] = nextMember;
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { profileUpdated: true }
        });
      }
      return fail(ERR.INVALID_ARGUMENT, `\u672A\u5B9E\u73B0\u7684\u547D\u4EE4: ${type}`);
    }
    module2.exports = {
      executeCommand,
      buildHead,
      buildCapabilities,
      projectSnapshot,
      projectMembersDomain,
      authorizeRoomRead,
      allocateSeatNo,
      findSeatNo,
      createRoomAggregate
    };
  }
});

// packages/room-application/index.js
var require_room_application = __commonJS({
  "packages/room-application/index.js"(exports2, module2) {
    "use strict";
    var {
      COMMAND_TYPES,
      ERR,
      fail,
      okResult,
      validateCommandEnvelope,
      isNonEmptyString
    } = require_room_contracts();
    var {
      executeCommand,
      buildHead,
      projectSnapshot,
      authorizeRoomRead
    } = require_room_domain();
    function createRoomApplication2(repo, options) {
      if (!repo || typeof repo.loadRoom !== "function") {
        throw new Error("RoomRepository required");
      }
      const appOptions = options || {};
      async function execute(rawEnvelope, actorContext) {
        const actorUserId = actorContext && actorContext.userId;
        if (!actorUserId) {
          return fail(ERR.UNAUTHENTICATED);
        }
        const validated = validateCommandEnvelope(rawEnvelope);
        if (!validated.ok) return validated;
        const envelope = validated.envelope;
        const existingCmd = await repo.loadCommand(envelope.commandId);
        if (existingCmd) {
          if (String(existingCmd.actorUserId) !== String(actorUserId) || existingCmd.roomId && envelope.roomId && String(existingCmd.roomId) !== String(envelope.roomId)) {
            return fail(ERR.COMMAND_ID_CONFLICT);
          }
          return existingCmd.result;
        }
        let room = null;
        if (envelope.type !== COMMAND_TYPES.CREATE_ROOM) {
          room = await repo.loadRoom(envelope.roomId);
        }
        const domainResult = executeCommand({
          room,
          envelope,
          actorUserId,
          roomIdFactory: repo.generateRoomId ? () => repo.generateRoomId() : void 0,
          now: appOptions.now || Date.now(),
          wordPairPicker: appOptions.wordPairPicker,
          random: appOptions.random
        });
        if (!domainResult.ok) {
          return {
            ...domainResult,
            commandId: envelope.commandId
          };
        }
        if (!(domainResult.effects && domainResult.effects.readOnly)) {
          await repo.persistRoom(domainResult.room, domainResult.effects || {});
        }
        const success = okResult({
          commandId: envelope.commandId,
          appliedRevision: domainResult.appliedRevision,
          changedDomains: domainResult.changedDomains || [],
          head: domainResult.head || buildHead(domainResult.room, actorUserId),
          effects: domainResult.effects || {},
          roomId: domainResult.room.roomId
        });
        if (domainResult.effects && domainResult.effects.card) {
          success.card = domainResult.effects.card;
        }
        if (domainResult.effects && domainResult.effects.spyGame) {
          success.spyGame = domainResult.effects.spyGame;
        }
        if (domainResult.effects && domainResult.effects.legacyPage) {
          success.currentPage = domainResult.effects.legacyPage;
        }
        ["settled", "tied", "finished", "autoVote", "already", "restarted"].forEach((key) => {
          if (domainResult.effects && domainResult.effects[key] != null) {
            success[key] = domainResult.effects[key];
          }
        });
        await repo.saveCommandResult({
          commandId: envelope.commandId,
          actorUserId,
          roomId: domainResult.room.roomId,
          type: envelope.type,
          result: success
        });
        return success;
      }
      async function readHead(roomId, actorContext) {
        const actorUserId = actorContext && actorContext.userId;
        if (!isNonEmptyString(roomId)) {
          return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
        }
        const room = await repo.loadRoom(roomId);
        const auth = authorizeRoomRead(room, actorUserId);
        if (!auth.ok) return auth;
        return okResult({ head: buildHead(auth.room, actorUserId) });
      }
      async function readSnapshot(roomId, actorContext, request) {
        const actorUserId = actorContext && actorContext.userId;
        if (!isNonEmptyString(roomId)) {
          return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
        }
        const room = await repo.loadRoom(roomId);
        const auth = authorizeRoomRead(room, actorUserId);
        if (!auth.ok) return auth;
        const domains = request && request.domains || ["members"];
        let extraDomainData = {};
        if (typeof repo.loadDomainData === "function") {
          extraDomainData = await repo.loadDomainData(roomId, domains);
        }
        const snapshot = projectSnapshot(auth.room, {
          actorUserId,
          domains,
          clientDomainRevisions: request && request.domainRevisions || {},
          extraDomainData
        });
        return okResult({ snapshot, head: buildHead(auth.room, actorUserId) });
      }
      async function heartbeat(roomId, actorContext, payload) {
        const actorUserId = actorContext && actorContext.userId;
        if (!isNonEmptyString(roomId)) {
          return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
        }
        if (!isNonEmptyString(actorUserId)) {
          return fail(ERR.UNAUTHENTICATED);
        }
        const room = await repo.loadRoom(roomId);
        const auth = authorizeRoomRead(room, actorUserId);
        if (!auth.ok) return auth;
        if (typeof repo.upsertPresence !== "function") {
          return fail(ERR.DEPENDENCY_UNAVAILABLE, "presence store unavailable");
        }
        const row = await repo.upsertPresence({
          roomId,
          userId: actorUserId,
          deviceSessionId: payload && payload.deviceSessionId
        });
        return okResult({
          presence: row,
          revision: auth.room.revision
        });
      }
      return { execute, readHead, readSnapshot, heartbeat };
    }
    function createInMemoryRoomRepository(options) {
      const rooms = /* @__PURE__ */ new Map();
      const commands = /* @__PURE__ */ new Map();
      const presence = /* @__PURE__ */ new Map();
      const domainExtras = /* @__PURE__ */ new Map();
      let seq = 1e7;
      return {
        rooms,
        commands,
        presence,
        domainExtras,
        generateRoomId() {
          if (options && typeof options.generateRoomId === "function") {
            return options.generateRoomId();
          }
          seq += 1;
          return String(seq);
        },
        async loadRoom(roomId) {
          const room = rooms.get(roomId);
          return room ? JSON.parse(JSON.stringify(room)) : null;
        },
        async loadCommand(commandId) {
          return commands.get(commandId) || null;
        },
        async saveCommandResult(row) {
          commands.set(row.commandId, row);
        },
        async persistRoom(room) {
          rooms.set(room.roomId, JSON.parse(JSON.stringify(room)));
        },
        async loadDomainData(roomId, domains) {
          const bag = domainExtras.get(roomId) || {};
          const out = {};
          (domains || []).forEach((d) => {
            if (d !== "members" && Object.prototype.hasOwnProperty.call(bag, d)) {
              out[d] = bag[d];
            }
          });
          return out;
        },
        async upsertPresence({ roomId, userId, deviceSessionId }) {
          const key = `${roomId}:${userId}:${deviceSessionId || "default"}`;
          const row = {
            roomId,
            userId,
            deviceSessionId: deviceSessionId || "default",
            lastSeenAt: Date.now(),
            online: true
          };
          presence.set(key, row);
          return row;
        },
        async listPresence(roomId) {
          return [...presence.values()].filter((p) => p.roomId === roomId);
        }
      };
    }
    module2.exports = {
      createRoomApplication: createRoomApplication2,
      createInMemoryRoomRepository
    };
  }
});

// packages/room-cloudbase-adapter/index.js
var require_room_cloudbase_adapter = __commonJS({
  "packages/room-cloudbase-adapter/index.js"(exports2, module2) {
    "use strict";
    var { MAX_SEATS } = require_room_contracts();
    var ROOMS = "rooms";
    var MEMBERS = "roomMembers";
    var COMMANDS = "roomCommands";
    var PRESENCE = "roomPresence";
    var SCORES = "roomScores";
    var MESSAGES = "roomMessages";
    var VOTES = "roomVotes";
    var ARTIFACTS = "roomArtifacts";
    var SECRETS = "roomSecrets";
    function createCloudBaseRoomRepository2(deps) {
      const db2 = deps.db;
      if (!db2) throw new Error("db required");
      async function generateRoomId(maxRetry) {
        const retries = maxRetry || 5;
        for (let i = 0; i < retries; i += 1) {
          const roomId = String(Math.floor(1e7 + Math.random() * 9e7));
          const exist = await db2.collection(ROOMS).where({ roomId }).limit(1).get();
          if (!exist.data || !exist.data.length) return roomId;
        }
        return String(Math.floor(1e7 + Math.random() * 9e7));
      }
      function toAggregate(roomDoc, memberDocs) {
        if (!roomDoc) return null;
        const membersByUserId = {};
        const seatMap = roomDoc.seatMap && typeof roomDoc.seatMap === "object" ? { ...roomDoc.seatMap } : {};
        (memberDocs || []).forEach((m) => {
          if (!m || !m.userId) return;
          const seatNo = m.playerIndex != null ? Number(m.playerIndex) : null;
          membersByUserId[m.userId] = {
            userId: m.userId,
            seatNo,
            role: m.role === "GOD" || m.role === "HOST" ? "HOST" : "PLAYER",
            nickName: m.nickName || `\u73A9\u5BB6${seatNo || ""}`,
            avatarUrl: m.avatarUrl || null,
            avatarColor: m.avatarColor || "#5EC159",
            avatarIndex: m.avatarIndex != null ? m.avatarIndex : null,
            joinedAt: m.joinedAt || null,
            _id: m._id
          };
          if (seatNo && !seatMap[String(seatNo)]) {
            seatMap[String(seatNo)] = m.userId;
          }
        });
        if (!Object.keys(seatMap).length) {
          Object.values(membersByUserId).forEach((m) => {
            if (m.seatNo) seatMap[String(m.seatNo)] = m.userId;
          });
        }
        return {
          _id: roomDoc._id,
          roomId: roomDoc.roomId,
          schemaVersion: roomDoc.schemaVersion || 1,
          protocolVersion: roomDoc.protocolVersion || 1,
          lifecycle: roomDoc.lifecycle || (roomDoc.status === "DISSOLVED" ? "DISSOLVED" : "LOBBY"),
          status: roomDoc.status || "CREATED",
          hostUserId: roomDoc.hostUserId || roomDoc.creatorId,
          creatorId: roomDoc.creatorId || roomDoc.hostUserId,
          seatMap,
          activeSessionId: roomDoc.activeSessionId || null,
          revision: roomDoc.revision != null ? roomDoc.revision : 0,
          workflow: roomDoc.workflow || null,
          domainRevisions: roomDoc.domainRevisions || null,
          progress: roomDoc.progress || null,
          workshopName: roomDoc.workshopName || "\u8111\u66B4\u5DE5\u4F5C\u574A",
          membersByUserId,
          selectedModeId: roomDoc.selectedModeId || null,
          currentPage: roomDoc.currentPage || null,
          brainstormProgressPage: roomDoc.brainstormProgressPage || null,
          spyGame: roomDoc.spyGame || null,
          spyAssignments: roomDoc.spyAssignments || null,
          secretsByUserId: null,
          createdAt: roomDoc.createdAt,
          updatedAt: roomDoc.updatedAt
        };
      }
      function secretsFromLegacyAssignments(spyAssignments) {
        const map = {};
        if (!spyAssignments || typeof spyAssignments !== "object") return map;
        Object.keys(spyAssignments).forEach((seat) => {
          const row = spyAssignments[seat];
          if (!row || !row.userId) return;
          map[row.userId] = {
            playerIndex: row.playerIndex != null ? Number(row.playerIndex) : Number(seat),
            userId: row.userId,
            role: row.role,
            word: row.word,
            blurb: row.blurb || "",
            name: row.name || ""
          };
        });
        return map;
      }
      async function loadSecretsByUserId(roomId) {
        try {
          const res = await db2.collection(SECRETS).where({ roomId }).limit(MAX_SEATS).get();
          const map = {};
          (res.data || []).forEach((doc) => {
            if (!doc || !doc.userId) return;
            map[doc.userId] = {
              playerIndex: doc.playerIndex != null ? Number(doc.playerIndex) : null,
              userId: doc.userId,
              role: doc.role,
              word: doc.word,
              blurb: doc.blurb || "",
              name: doc.name || ""
            };
          });
          return map;
        } catch (e) {
          console.warn("load roomSecrets failed", e);
          return {};
        }
      }
      async function loadRoom(roomId) {
        const roomRes = await db2.collection(ROOMS).where({ roomId }).limit(1).get();
        if (!roomRes.data || !roomRes.data.length) return null;
        const roomDoc = roomRes.data[0];
        const membersRes = await db2.collection(MEMBERS).where({ roomId }).limit(MAX_SEATS).get();
        const agg = toAggregate(roomDoc, membersRes.data || []);
        let secretsByUserId = await loadSecretsByUserId(roomId);
        if (!Object.keys(secretsByUserId).length) {
          secretsByUserId = secretsFromLegacyAssignments(roomDoc.spyAssignments);
        }
        agg.secretsByUserId = Object.keys(secretsByUserId).length ? secretsByUserId : null;
        return agg;
      }
      async function loadCommand(commandId) {
        try {
          const res = await db2.collection(COMMANDS).doc(commandId).get();
          return res && res.data ? res.data : null;
        } catch (e) {
          return null;
        }
      }
      async function saveCommandResult(row) {
        const now = Date.now();
        await db2.collection(COMMANDS).doc(row.commandId).set({
          data: {
            commandId: row.commandId,
            actorUserId: row.actorUserId,
            roomId: row.roomId,
            type: row.type,
            result: row.result,
            createdAt: now,
            updatedAt: now
          }
        });
      }
      async function persistRoom(room, effects) {
        const now = room.updatedAt || Date.now();
        const roomFields = {
          roomId: room.roomId,
          schemaVersion: room.schemaVersion,
          protocolVersion: room.protocolVersion,
          lifecycle: room.lifecycle,
          status: room.status,
          hostUserId: room.hostUserId,
          creatorId: room.creatorId || room.hostUserId,
          seatMap: room.seatMap,
          activeSessionId: room.activeSessionId,
          revision: room.revision,
          workflow: room.workflow,
          domainRevisions: room.domainRevisions,
          progress: room.progress,
          workshopName: room.workshopName,
          selectedModeId: room.selectedModeId || null,
          currentPage: room.currentPage || null,
          brainstormProgressPage: room.brainstormProgressPage || null,
          spyGame: room.spyGame || null,
          // 兼容现网 spyGameAction：过渡期双写；权威密牌以 roomSecrets 为准
          spyAssignments: room.spyAssignments || null,
          updatedAt: now
        };
        if (effects && effects.created) {
          roomFields.createdAt = room.createdAt || now;
          await db2.collection(ROOMS).add({ data: roomFields });
        } else if (room._id) {
          await db2.collection(ROOMS).doc(room._id).update({ data: roomFields });
        } else {
          await db2.collection(ROOMS).where({ roomId: room.roomId }).update({ data: roomFields });
        }
        if (effects && effects.dissolved) {
          const all = await db2.collection(MEMBERS).where({ roomId: room.roomId }).limit(20).get();
          for (const m of all.data || []) {
            await db2.collection(MEMBERS).doc(m._id).remove();
          }
          return;
        }
        const existing = await db2.collection(MEMBERS).where({ roomId: room.roomId }).limit(20).get();
        const byUser = {};
        (existing.data || []).forEach((m) => {
          byUser[m.userId] = m;
        });
        const desiredIds = new Set(Object.keys(room.membersByUserId || {}));
        for (const userId of Object.keys(byUser)) {
          if (!desiredIds.has(userId)) {
            await db2.collection(MEMBERS).doc(byUser[userId]._id).remove();
          }
        }
        for (const userId of desiredIds) {
          const m = room.membersByUserId[userId];
          const data = {
            roomId: room.roomId,
            userId,
            role: m.role === "HOST" ? "GOD" : "PLAYER",
            nickName: m.nickName,
            avatarUrl: m.avatarUrl,
            avatarColor: m.avatarColor,
            avatarIndex: m.avatarIndex,
            playerIndex: m.seatNo,
            joinedAt: m.joinedAt || now,
            lastSeenAt: now
          };
          if (byUser[userId]) {
            await db2.collection(MEMBERS).doc(byUser[userId]._id).update({ data });
          } else {
            await db2.collection(MEMBERS).add({ data });
          }
        }
        if (effects && effects.scoreUpsert && room.scoresByKey && effects.scoreKey) {
          const row = room.scoresByKey[effects.scoreKey];
          if (row) {
            const docId = `${room.roomId}_${row.turnId}_${row.scorerUserId}`.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 128);
            try {
              await db2.collection(SCORES).doc(docId).set({
                data: {
                  roomId: room.roomId,
                  turnId: row.turnId,
                  userId: row.scorerUserId,
                  currentPlayerIndex: row.activeSeatNo,
                  score: row.score,
                  updatedAt: row.updatedAt,
                  createdAt: row.updatedAt
                }
              });
            } catch (e) {
              console.warn("persist score failed", e);
            }
          }
        }
        if (effects && effects.messageAppended && Array.isArray(room.messages)) {
          const msg = room.messages.find((m) => m && m.id === effects.messageId);
          if (msg) {
            try {
              await db2.collection(MESSAGES).add({
                data: {
                  roomId: room.roomId,
                  messageId: msg.id,
                  text: msg.text,
                  at: msg.at,
                  round: msg.round,
                  phase: msg.phase,
                  anonKey: msg.anonKey
                }
              });
            } catch (e) {
              console.warn("persist message failed", e);
            }
          }
        }
        if (effects && effects.voteUpsert && room.votesByKey && effects.voteKey) {
          const row = room.votesByKey[effects.voteKey];
          if (row) {
            const docId = `${row.voteSessionId}_${row.voterUserId}`.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 128);
            try {
              await db2.collection(VOTES).doc(docId).set({
                data: {
                  roomId: room.roomId,
                  voteSessionId: row.voteSessionId,
                  userId: row.voterUserId,
                  seatNo: row.seatNo,
                  vote: row.vote,
                  at: row.at
                }
              });
            } catch (e) {
              console.warn("persist vote failed", e);
            }
          }
        }
        if (effects && effects.artifactAppended && Array.isArray(room.artifacts)) {
          const art = room.artifacts.find((a) => a && a.operationId === effects.operationId);
          if (art) {
            try {
              await db2.collection(ARTIFACTS).add({
                data: {
                  roomId: room.roomId,
                  ...art
                }
              });
            } catch (e) {
              console.warn("persist artifact failed", e);
            }
          }
        }
        if (effects && effects.secretsClear) {
          try {
            const existing2 = await db2.collection(SECRETS).where({ roomId: room.roomId }).limit(MAX_SEATS).get();
            for (const doc of existing2.data || []) {
              await db2.collection(SECRETS).doc(doc._id).remove();
            }
          } catch (e) {
            console.warn("clear roomSecrets failed", e);
          }
        } else if (effects && effects.secretsUpsert && room.secretsByUserId) {
          try {
            const existing2 = await db2.collection(SECRETS).where({ roomId: room.roomId }).limit(MAX_SEATS).get();
            for (const doc of existing2.data || []) {
              await db2.collection(SECRETS).doc(doc._id).remove();
            }
          } catch (e) {
            console.warn("clear roomSecrets failed", e);
          }
          for (const userId of Object.keys(room.secretsByUserId)) {
            const row = room.secretsByUserId[userId];
            if (!row) continue;
            const docId = `${room.roomId}_${userId}`.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 128);
            try {
              await db2.collection(SECRETS).doc(docId).set({
                data: {
                  roomId: room.roomId,
                  userId,
                  playerIndex: row.playerIndex != null ? Number(row.playerIndex) : null,
                  role: row.role,
                  word: row.word,
                  blurb: row.blurb || "",
                  name: row.name || "",
                  updatedAt: now
                }
              });
            } catch (e) {
              console.warn("persist roomSecret failed", e);
            }
          }
        }
      }
      async function loadDomainData(roomId, domains) {
        const out = {};
        const wanted = domains || [];
        if (wanted.includes("scores")) {
          try {
            const res = await db2.collection(SCORES).where({ roomId }).limit(200).get();
            out.scores = res.data || [];
          } catch (e) {
            out.scores = [];
          }
        }
        return out;
      }
      async function upsertPresence({ roomId, userId, deviceSessionId }) {
        const device = deviceSessionId || "default";
        const docId = `${roomId}_${userId}_${device}`.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 128);
        const now = Date.now();
        const data = {
          roomId,
          userId,
          deviceSessionId: device,
          lastSeenAt: now,
          online: true,
          updatedAt: now
        };
        try {
          await db2.collection(PRESENCE).doc(docId).set({ data });
        } catch (e) {
          await db2.collection(PRESENCE).add({ data: { ...data, _fallbackId: docId } });
        }
        return data;
      }
      async function listPresence(roomId) {
        const res = await db2.collection(PRESENCE).where({ roomId }).limit(50).get();
        return res.data || [];
      }
      return {
        generateRoomId,
        loadRoom,
        loadCommand,
        saveCommandResult,
        persistRoom,
        loadDomainData,
        upsertPresence,
        listPresence
      };
    }
    module2.exports = {
      createCloudBaseRoomRepository: createCloudBaseRoomRepository2
    };
  }
});

// cloudfunctions/roomPresence/src/entry.js
var cloud = require("wx-server-sdk");
var { createRoomApplication } = require_room_application();
var { createCloudBaseRoomRepository } = require_room_cloudbase_adapter();
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
var db = cloud.database();
var app = createRoomApplication(createCloudBaseRoomRepository({ db, cloud }));
exports.main = async (event) => {
  const wxContext = cloud.getWXContext();
  const userId = wxContext.FROM_OPENID || wxContext.OPENID || "";
  const roomId = event && event.roomId;
  try {
    return await app.heartbeat(roomId, { userId }, {
      deviceSessionId: event && event.deviceSessionId
    });
  } catch (e) {
    console.error("roomPresence error", e);
    return {
      ok: false,
      errCode: e.errCode || e.code || "INTERNAL_ERROR",
      errMsg: e.errMsg || e.message || "roomPresence failed"
    };
  }
};
