/** Generated by scripts/build-cloud-functions.js — do not edit. */
"use strict";
var __getOwnPropNames = Object.getOwnPropertyNames;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};

// packages/room-contracts/index.js
var require_room_contracts = __commonJS({
  "packages/room-contracts/index.js"(exports2, module2) {
    "use strict";
    var PROTOCOL_VERSION = 2;
    var SCHEMA_VERSION = 2;
    var MAX_SEATS = 6;
    var LIFECYCLE = {
      LOBBY: "LOBBY",
      ACTIVE: "ACTIVE",
      DISSOLVED: "DISSOLVED"
    };
    var COMMAND_TYPES = {
      CREATE_ROOM: "CREATE_ROOM",
      JOIN_ROOM: "JOIN_ROOM",
      LEAVE_ROOM: "LEAVE_ROOM",
      REORDER_SEATS: "REORDER_SEATS",
      DISSOLVE_ROOM: "DISSOLVE_ROOM",
      UPDATE_MEMBER_PROFILE: "UPDATE_MEMBER_PROFILE",
      // Partner
      SUBMIT_SCORE: "SUBMIT_SCORE",
      START_STATEMENT: "START_STATEMENT",
      ADVANCE_TURN: "ADVANCE_TURN",
      POST_MESSAGE: "POST_MESSAGE",
      SUBMIT_CLOSING_VOTE: "SUBMIT_CLOSING_VOTE",
      APPEND_ARTIFACT: "APPEND_ARTIFACT"
    };
    var ERR = {
      INVALID_ARGUMENT: "INVALID_ARGUMENT",
      UNAUTHENTICATED: "UNAUTHENTICATED",
      ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
      ROOM_FULL: "ROOM_FULL",
      NOT_MEMBER: "NOT_MEMBER",
      HOST_REQUIRED: "HOST_REQUIRED",
      HOST_CANNOT_LEAVE: "HOST_CANNOT_LEAVE",
      SESSION_MISMATCH: "SESSION_MISMATCH",
      REVISION_CONFLICT: "REVISION_CONFLICT",
      INVALID_TRANSITION: "INVALID_TRANSITION",
      COMMAND_ID_CONFLICT: "COMMAND_ID_CONFLICT",
      COMMAND_IN_PROGRESS: "COMMAND_IN_PROGRESS",
      RATE_LIMITED: "RATE_LIMITED",
      DEPENDENCY_UNAVAILABLE: "DEPENDENCY_UNAVAILABLE",
      INTERNAL_ERROR: "INTERNAL_ERROR",
      ROOM_DISSOLVED: "ROOM_DISSOLVED",
      SELF_SCORE: "SELF_SCORE",
      ALREADY_VOTED: "ALREADY_VOTED"
    };
    var ERR_MSG = {
      [ERR.INVALID_ARGUMENT]: "\u53C2\u6570\u4E0D\u5408\u6CD5",
      [ERR.UNAUTHENTICATED]: "\u672A\u767B\u5F55",
      [ERR.ROOM_NOT_FOUND]: "\u623F\u95F4\u4E0D\u5B58\u5728",
      [ERR.ROOM_FULL]: "\u623F\u95F4\u5DF2\u6EE1",
      [ERR.NOT_MEMBER]: "\u975E\u623F\u95F4\u6210\u5458",
      [ERR.HOST_REQUIRED]: "\u4EC5\u623F\u4E3B\u53EF\u64CD\u4F5C",
      [ERR.HOST_CANNOT_LEAVE]: "\u623F\u4E3B\u8BF7\u4F7F\u7528\u89E3\u6563\u623F\u95F4",
      [ERR.SESSION_MISMATCH]: "\u573A\u6B21\u5DF2\u53D8\u66F4",
      [ERR.REVISION_CONFLICT]: "\u623F\u95F4\u72B6\u6001\u5DF2\u66F4\u65B0",
      [ERR.INVALID_TRANSITION]: "\u5F53\u524D\u6B65\u9AA4\u4E0D\u5141\u8BB8\u8BE5\u64CD\u4F5C",
      [ERR.COMMAND_ID_CONFLICT]: "commandId \u51B2\u7A81",
      [ERR.COMMAND_IN_PROGRESS]: "\u547D\u4EE4\u5904\u7406\u4E2D",
      [ERR.RATE_LIMITED]: "\u8BF7\u6C42\u8FC7\u4E8E\u9891\u7E41",
      [ERR.DEPENDENCY_UNAVAILABLE]: "\u4F9D\u8D56\u6682\u65F6\u4E0D\u53EF\u7528",
      [ERR.INTERNAL_ERROR]: "\u670D\u52A1\u5F02\u5E38",
      [ERR.ROOM_DISSOLVED]: "\u623F\u95F4\u5DF2\u89E3\u6563",
      [ERR.SELF_SCORE]: "\u5F53\u524D\u51FA\u724C\u73A9\u5BB6\u65E0\u9700\u6253\u5206",
      [ERR.ALREADY_VOTED]: "\u60A8\u5DF2\u8868\u6001"
    };
    function fail(errCode, errMsg, extra) {
      return {
        ok: false,
        errCode,
        errMsg: errMsg || ERR_MSG[errCode] || errCode,
        retryable: errCode === ERR.DEPENDENCY_UNAVAILABLE || errCode === ERR.COMMAND_IN_PROGRESS,
        ...extra || {}
      };
    }
    function okResult(fields) {
      return { ok: true, ...fields || {} };
    }
    function isNonEmptyString(v) {
      return typeof v === "string" && v.trim().length > 0;
    }
    function isCommandId(v) {
      return typeof v === "string" && v.trim().length >= 4 && v.trim().length <= 64;
    }
    function validateCommandEnvelope(raw) {
      if (!raw || typeof raw !== "object") {
        return fail(ERR.INVALID_ARGUMENT, "command envelope \u5FC5\u586B");
      }
      const type = raw.type;
      if (!Object.prototype.hasOwnProperty.call(COMMAND_TYPES, type) && !Object.values(COMMAND_TYPES).includes(type)) {
        return fail(ERR.INVALID_ARGUMENT, `\u672A\u77E5\u547D\u4EE4\u7C7B\u578B: ${type}`);
      }
      if (!isCommandId(raw.commandId)) {
        return fail(ERR.INVALID_ARGUMENT, "commandId \u5FC5\u586B");
      }
      const protocolVersion = raw.protocolVersion == null ? PROTOCOL_VERSION : Number(raw.protocolVersion);
      if (protocolVersion !== PROTOCOL_VERSION) {
        return fail(ERR.INVALID_ARGUMENT, `\u4EC5\u652F\u6301 protocolVersion=${PROTOCOL_VERSION}`);
      }
      if (type !== COMMAND_TYPES.CREATE_ROOM && !isNonEmptyString(raw.roomId)) {
        return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
      }
      const needsRevision = type !== COMMAND_TYPES.CREATE_ROOM && type !== COMMAND_TYPES.JOIN_ROOM && type !== COMMAND_TYPES.SUBMIT_SCORE && type !== COMMAND_TYPES.POST_MESSAGE && type !== COMMAND_TYPES.SUBMIT_CLOSING_VOTE && type !== COMMAND_TYPES.APPEND_ARTIFACT;
      if (needsRevision) {
        if (raw.expectedRevision == null || !Number.isFinite(Number(raw.expectedRevision))) {
          return fail(ERR.INVALID_ARGUMENT, "expectedRevision \u5FC5\u586B");
        }
      }
      return okResult({
        envelope: {
          protocolVersion: PROTOCOL_VERSION,
          roomId: raw.roomId ? String(raw.roomId).trim() : "",
          sessionId: raw.sessionId || null,
          commandId: String(raw.commandId),
          expectedRevision: raw.expectedRevision == null ? null : Number(raw.expectedRevision),
          type,
          payload: raw.payload && typeof raw.payload === "object" ? raw.payload : {},
          clientSentAt: raw.clientSentAt != null ? Number(raw.clientSentAt) : null
        }
      });
    }
    function emptyDomainRevisions() {
      return {
        members: 0,
        session: 0,
        scores: 0,
        contributions: 0,
        artifacts: 0,
        messages: 0,
        votes: 0
      };
    }
    module2.exports = {
      PROTOCOL_VERSION,
      SCHEMA_VERSION,
      MAX_SEATS,
      LIFECYCLE,
      COMMAND_TYPES,
      ERR,
      ERR_MSG,
      fail,
      okResult,
      validateCommandEnvelope,
      emptyDomainRevisions,
      isNonEmptyString
    };
  }
});

// packages/room-domain/index.js
var require_room_domain = __commonJS({
  "packages/room-domain/index.js"(exports2, module2) {
    "use strict";
    var {
      PROTOCOL_VERSION,
      SCHEMA_VERSION,
      MAX_SEATS,
      LIFECYCLE,
      COMMAND_TYPES,
      ERR,
      fail,
      okResult,
      emptyDomainRevisions,
      isNonEmptyString
    } = require_room_contracts();
    var AVATAR_COLORS = [
      "#5EC159",
      "#4A90E2",
      "#E24A4A",
      "#E2B84A",
      "#9B59B6",
      "#1ABC9C",
      "#E67E22",
      "#3498DB"
    ];
    function allocateSeatNo(seatMap) {
      const used = new Set(
        Object.keys(seatMap || {}).map((k) => parseInt(k, 10)).filter((n) => Number.isFinite(n))
      );
      for (let seat = 1; seat <= MAX_SEATS; seat += 1) {
        if (!used.has(seat)) return seat;
      }
      return null;
    }
    function pickAvatarColor(seatMap, membersByUserId) {
      const used = [];
      Object.values(seatMap || {}).forEach((userId) => {
        const m = membersByUserId[userId];
        if (m && m.avatarColor) used.push(m.avatarColor);
      });
      const available = AVATAR_COLORS.filter((c) => !used.includes(c));
      return available.length ? available[0] : AVATAR_COLORS[0];
    }
    function buildCapabilities(room, actorUserId) {
      const seatNo = findSeatNo(room.seatMap, actorUserId);
      const isHost = room.hostUserId && String(room.hostUserId) === String(actorUserId);
      const isMember = !!(seatNo || isHost);
      const inLobby = room.lifecycle === LIFECYCLE.LOBBY;
      return {
        joinRoom: {
          allowed: room.lifecycle !== LIFECYCLE.DISSOLVED && memberCount(room.seatMap) < MAX_SEATS,
          reason: room.lifecycle === LIFECYCLE.DISSOLVED ? "ROOM_DISSOLVED" : memberCount(room.seatMap) >= MAX_SEATS ? "ROOM_FULL" : null
        },
        leaveRoom: {
          allowed: isMember && !isHost,
          reason: !isMember ? "NOT_MEMBER" : isHost ? "HOST_CANNOT_LEAVE" : null
        },
        reorderSeats: {
          allowed: isHost && inLobby,
          reason: !isHost ? "HOST_ONLY" : !inLobby ? "INVALID_TRANSITION" : null
        },
        dissolveRoom: {
          allowed: isHost,
          reason: isHost ? null : "HOST_ONLY"
        },
        submitScore: {
          allowed: isMember && !(room.workflow && room.workflow.activeSeatNo != null && Number(seatNo) === Number(room.workflow.activeSeatNo)),
          reason: !isMember ? "NOT_MEMBER" : room.workflow && Number(seatNo) === Number(room.workflow.activeSeatNo) ? "SELF_SCORE" : null
        },
        startStatement: {
          allowed: isHost && room.progress && room.progress.requiredScoreCount > 0 && room.progress.scoredCount >= room.progress.requiredScoreCount,
          reason: !isHost ? "HOST_ONLY" : "SCORES_INCOMPLETE"
        }
      };
    }
    function buildHead(room, actorUserId) {
      const seatNo = findSeatNo(room.seatMap, actorUserId);
      const isHost = room.hostUserId && String(room.hostUserId) === String(actorUserId);
      return {
        protocolVersion: room.protocolVersion || PROTOCOL_VERSION,
        roomId: room.roomId,
        schemaVersion: room.schemaVersion || SCHEMA_VERSION,
        revision: room.revision,
        lifecycle: room.lifecycle,
        activeSessionId: room.activeSessionId || null,
        workflow: room.workflow || null,
        domainRevisions: room.domainRevisions || emptyDomainRevisions(),
        progress: room.progress || {
          scoredCount: 0,
          requiredScoreCount: 0,
          votedCount: 0,
          requiredVoteCount: 0
        },
        actor: {
          role: isHost ? "HOST" : seatNo ? "PLAYER" : "NONE",
          seatNo: seatNo || null
        },
        capabilities: buildCapabilities(room, actorUserId),
        serverTime: Date.now()
      };
    }
    function projectMembersDomain(room, actorUserId) {
      const list = [];
      const seatMap = room.seatMap || {};
      Object.keys(seatMap).map((k) => parseInt(k, 10)).filter((n) => Number.isFinite(n)).sort((a, b) => a - b).forEach((seatNo) => {
        const userId = seatMap[String(seatNo)];
        const m = room.membersByUserId && room.membersByUserId[userId] || {};
        list.push({
          seatNo,
          nickName: m.nickName || `\u73A9\u5BB6${seatNo}`,
          avatarColor: m.avatarColor || "#5EC159",
          avatarUrl: m.avatarUrl || null,
          avatarIndex: m.avatarIndex != null ? m.avatarIndex : null,
          role: m.role === "HOST" || seatNo === 1 ? "HOST" : "PLAYER",
          isMe: String(userId) === String(actorUserId),
          online: m.online !== false
          // 不返回 userId / openid
        });
      });
      return list;
    }
    function projectSnapshot(room, options) {
      const actorUserId = options && options.actorUserId;
      const requested = options && options.domains && options.domains.length ? options.domains : ["members"];
      const clientRevs = options && options.clientDomainRevisions || {};
      const serverRevs = room.domainRevisions || emptyDomainRevisions();
      const extra = options && options.extraDomainData || {};
      const domains = {};
      requested.forEach((name) => {
        const serverRev = serverRevs[name] != null ? serverRevs[name] : 0;
        const clientRev = clientRevs[name] != null ? clientRevs[name] : -1;
        if (clientRev >= serverRev && clientRev >= 0) {
          return;
        }
        let data = null;
        if (name === "members") {
          data = projectMembersDomain(room, actorUserId);
        } else if (Object.prototype.hasOwnProperty.call(extra, name)) {
          data = extra[name];
        } else {
          data = name === "scores" || name === "votes" ? {} : [];
        }
        domains[name] = { revision: serverRev, data };
      });
      return {
        roomId: room.roomId,
        revision: room.revision,
        domains,
        serverTime: Date.now()
      };
    }
    function authorizeRoomRead(room, actorUserId) {
      if (!isNonEmptyString(actorUserId)) {
        return fail(ERR.UNAUTHENTICATED);
      }
      if (!room) {
        return fail(ERR.ROOM_NOT_FOUND);
      }
      if (room.lifecycle === LIFECYCLE.DISSOLVED || room.status === "DISSOLVED") {
        return fail(ERR.ROOM_DISSOLVED);
      }
      const seatNo = findSeatNo(room.seatMap, actorUserId);
      const isHost = room.hostUserId && String(room.hostUserId) === String(actorUserId);
      if (!seatNo && !isHost) {
        return fail(ERR.NOT_MEMBER);
      }
      return okResult({ room });
    }
    function findSeatNo(seatMap, userId) {
      if (!userId || !seatMap) return null;
      const entries = Object.entries(seatMap);
      for (let i = 0; i < entries.length; i += 1) {
        if (String(entries[i][1]) === String(userId)) {
          return parseInt(entries[i][0], 10);
        }
      }
      return null;
    }
    function memberCount(seatMap) {
      return Object.keys(seatMap || {}).length;
    }
    function assertActor(actorUserId) {
      if (!isNonEmptyString(actorUserId)) {
        return fail(ERR.UNAUTHENTICATED);
      }
      return null;
    }
    function createRoomAggregate({ roomId, actorUserId, payload, now }) {
      const nickName = isNonEmptyString(payload.nickName) ? String(payload.nickName).trim() : "\u73A9\u5BB61";
      const avatarUrl = payload.avatarUrl || null;
      const avatarColor = pickAvatarColor({}, {});
      const member = {
        userId: actorUserId,
        seatNo: 1,
        role: "HOST",
        nickName,
        avatarUrl,
        avatarColor,
        avatarIndex: avatarUrl ? null : 0,
        joinedAt: now
      };
      return {
        roomId,
        schemaVersion: SCHEMA_VERSION,
        protocolVersion: PROTOCOL_VERSION,
        lifecycle: LIFECYCLE.LOBBY,
        // 兼容旧字段
        status: "CREATED",
        hostUserId: actorUserId,
        creatorId: actorUserId,
        seatMap: { "1": actorUserId },
        activeSessionId: null,
        revision: 1,
        workflow: null,
        domainRevisions: { ...emptyDomainRevisions(), members: 1 },
        progress: {
          scoredCount: 0,
          requiredScoreCount: 0,
          votedCount: 0,
          requiredVoteCount: 0
        },
        workshopName: isNonEmptyString(payload.workshopName) ? String(payload.workshopName).trim() : "\u8111\u66B4\u5DE5\u4F5C\u574A",
        membersByUserId: { [actorUserId]: member },
        createdAt: now,
        updatedAt: now
      };
    }
    function executeCommand({ room, envelope, actorUserId, roomIdFactory, now }) {
      const authErr = assertActor(actorUserId);
      if (authErr) return authErr;
      const ts = now || Date.now();
      const { type, payload, expectedRevision, commandId, roomId } = envelope;
      if (type === COMMAND_TYPES.CREATE_ROOM) {
        if (room) {
          return fail(ERR.INVALID_ARGUMENT, "\u623F\u95F4\u5DF2\u5B58\u5728");
        }
        const newRoomId = roomIdFactory ? roomIdFactory() : null;
        if (!isNonEmptyString(newRoomId)) {
          return fail(ERR.INTERNAL_ERROR, "\u65E0\u6CD5\u751F\u6210 roomId");
        }
        const next = createRoomAggregate({
          roomId: newRoomId,
          actorUserId,
          payload: payload || {},
          now: ts
        });
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { created: true }
        });
      }
      if (!room) {
        return fail(ERR.ROOM_NOT_FOUND);
      }
      if (room.lifecycle === LIFECYCLE.DISSOLVED || room.status === "DISSOLVED") {
        return fail(ERR.ROOM_DISSOLVED);
      }
      if (type === COMMAND_TYPES.JOIN_ROOM) {
        const existingSeat = findSeatNo(room.seatMap, actorUserId);
        if (existingSeat) {
          const membersByUserId2 = { ...room.membersByUserId };
          const prev = membersByUserId2[actorUserId] || {};
          const nextMember = { ...prev };
          if (isNonEmptyString(payload.nickName)) {
            nextMember.nickName = String(payload.nickName).trim();
          }
          if (payload.avatarUrl !== void 0) {
            nextMember.avatarUrl = payload.avatarUrl || null;
          }
          membersByUserId2[actorUserId] = nextMember;
          const next2 = {
            ...room,
            membersByUserId: membersByUserId2,
            updatedAt: ts
          };
          return okResult({
            commandId,
            appliedRevision: room.revision,
            changedDomains: [],
            room: next2,
            head: buildHead(next2, actorUserId),
            effects: { alreadyMember: true, seatNo: existingSeat }
          });
        }
        if (memberCount(room.seatMap) >= MAX_SEATS) {
          return fail(ERR.ROOM_FULL);
        }
        if (room.lifecycle !== LIFECYCLE.LOBBY && room.lifecycle !== LIFECYCLE.ACTIVE) {
          return fail(ERR.INVALID_TRANSITION);
        }
        const seatNo = allocateSeatNo(room.seatMap);
        if (seatNo == null) return fail(ERR.ROOM_FULL);
        const nickName = isNonEmptyString(payload.nickName) ? String(payload.nickName).trim() : `\u73A9\u5BB6${seatNo}`;
        const avatarUrl = payload.avatarUrl || null;
        const avatarColor = pickAvatarColor(room.seatMap, room.membersByUserId || {});
        const member = {
          userId: actorUserId,
          seatNo,
          role: "PLAYER",
          nickName,
          avatarUrl,
          avatarColor,
          avatarIndex: avatarUrl ? null : Math.min(seatNo - 1, 8),
          joinedAt: ts
        };
        const seatMap = { ...room.seatMap, [String(seatNo)]: actorUserId };
        const membersByUserId = { ...room.membersByUserId || {}, [actorUserId]: member };
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          seatMap,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { joined: true, seatNo }
        });
      }
      {
        const factTypes = [
          COMMAND_TYPES.SUBMIT_SCORE,
          COMMAND_TYPES.POST_MESSAGE,
          COMMAND_TYPES.SUBMIT_CLOSING_VOTE,
          COMMAND_TYPES.APPEND_ARTIFACT
        ];
        if (factTypes.includes(type)) {
          const actorSeat2 = findSeatNo(room.seatMap, actorUserId);
          const isHost2 = String(room.hostUserId) === String(actorUserId);
          if (!actorSeat2 && !isHost2) {
            return fail(ERR.NOT_MEMBER);
          }
          if (type === COMMAND_TYPES.SUBMIT_SCORE) {
            const score = parseInt(payload.score, 10);
            if (!Number.isFinite(score) || score < 0 || score > 5) {
              return fail(ERR.INVALID_ARGUMENT, "score \u9700\u4E3A 0\uFF5E5");
            }
            const activeSeatNo = room.workflow && room.workflow.activeSeatNo != null ? Number(room.workflow.activeSeatNo) : payload.activeSeatNo != null ? Number(payload.activeSeatNo) : null;
            if (activeSeatNo != null && Number(actorSeat2) === Number(activeSeatNo)) {
              return fail(ERR.SELF_SCORE);
            }
            const turnId = room.workflow && room.workflow.turnId || payload.turnId || `turn_r${room.workflow && room.workflow.roundNo || 1}_s${activeSeatNo || 0}`;
            const scores = { ...room.scoresByKey || {} };
            const key = `${turnId}:${actorUserId}`;
            scores[key] = {
              turnId,
              scorerUserId: actorUserId,
              activeSeatNo,
              score,
              updatedAt: ts
            };
            const required = Math.max(0, memberCount(room.seatMap) - 1);
            const scoredUserIds = /* @__PURE__ */ new Set();
            Object.keys(scores).forEach((k) => {
              const row = scores[k];
              if (row && row.turnId === turnId) scoredUserIds.add(row.scorerUserId);
            });
            const progress = {
              scoredCount: scoredUserIds.size,
              requiredScoreCount: required,
              votedCount: room.progress && room.progress.votedCount || 0,
              requiredVoteCount: room.progress && room.progress.requiredVoteCount || 0,
              turnId
            };
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              scores: (room.domainRevisions && room.domainRevisions.scores || 0) + 1
            };
            const next = {
              ...room,
              scoresByKey: scores,
              progress,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["scores"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: {
                scoreUpsert: true,
                scoreKey: key,
                scoredCount: progress.scoredCount,
                totalRequired: required
              }
            });
          }
          if (type === COMMAND_TYPES.POST_MESSAGE) {
            const text = typeof payload.text === "string" ? payload.text.trim() : "";
            if (!text) return fail(ERR.INVALID_ARGUMENT, "\u5185\u5BB9\u4E0D\u80FD\u4E3A\u7A7A");
            if (text.length > 40) return fail(ERR.INVALID_ARGUMENT, "\u6700\u591A 40 \u5B57");
            const messageId = payload.messageId || `msg_${commandId}`;
            const messages = Array.isArray(room.messages) ? room.messages.slice() : [];
            if (!messages.some((m) => m && m.id === messageId)) {
              messages.push({
                id: messageId,
                text,
                at: ts,
                round: payload.round != null ? Number(payload.round) : 0,
                phase: payload.phase === "discussion" ? "discussion" : "play",
                anonKey: payload.anonKey || null
              });
            }
            const trimmed = messages.slice(-40);
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              messages: (room.domainRevisions && room.domainRevisions.messages || 0) + 1
            };
            const next = {
              ...room,
              messages: trimmed,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["messages"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: { messageAppended: true, messageId }
            });
          }
          if (type === COMMAND_TYPES.SUBMIT_CLOSING_VOTE) {
            const vote = String(payload.vote || "");
            if (vote !== "pass" && vote !== "question") {
              return fail(ERR.INVALID_ARGUMENT, "vote \u9700\u4E3A pass \u6216 question");
            }
            const voteSessionId = room.workflow && room.workflow.voteSessionId || payload.voteSessionId || `vote_${room.roomId}`;
            const votes = { ...room.votesByKey || {} };
            const key = `${voteSessionId}:${actorUserId}`;
            if (votes[key]) {
              return fail(ERR.ALREADY_VOTED);
            }
            votes[key] = {
              voteSessionId,
              voterUserId: actorUserId,
              seatNo: actorSeat2,
              vote,
              at: ts
            };
            const required = memberCount(room.seatMap);
            const votedCount = Object.keys(votes).filter((k) => votes[k].voteSessionId === voteSessionId).length;
            const progress = {
              ...room.progress || {},
              votedCount,
              requiredVoteCount: required
            };
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              votes: (room.domainRevisions && room.domainRevisions.votes || 0) + 1
            };
            const next = {
              ...room,
              votesByKey: votes,
              progress,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["votes"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: { voteUpsert: true, voteKey: key, votedCount, totalMembers: required }
            });
          }
          if (type === COMMAND_TYPES.APPEND_ARTIFACT) {
            const operationId = payload.operationId || commandId;
            const artifacts = Array.isArray(room.artifacts) ? room.artifacts.slice() : [];
            if (!artifacts.some((a) => a && a.operationId === operationId)) {
              artifacts.push({
                operationId,
                kind: payload.kind || "text",
                turnId: payload.turnId || null,
                stage: payload.stage || "play",
                body: payload.body || null,
                at: ts
              });
            }
            const domainRevisions = {
              ...room.domainRevisions || emptyDomainRevisions(),
              artifacts: (room.domainRevisions && room.domainRevisions.artifacts || 0) + 1
            };
            const next = {
              ...room,
              artifacts,
              domainRevisions,
              revision: room.revision + 1,
              updatedAt: ts
            };
            return okResult({
              commandId,
              appliedRevision: next.revision,
              changedDomains: ["artifacts"],
              room: next,
              head: buildHead(next, actorUserId),
              effects: { artifactAppended: true, operationId }
            });
          }
        }
      }
      const actorSeat = findSeatNo(room.seatMap, actorUserId);
      const isHost = String(room.hostUserId) === String(actorUserId);
      if (!actorSeat && !isHost) {
        return fail(ERR.NOT_MEMBER);
      }
      if (expectedRevision == null || Number(expectedRevision) !== Number(room.revision)) {
        return fail(ERR.REVISION_CONFLICT, void 0, {
          latestHead: buildHead(room, actorUserId)
        });
      }
      if (type === COMMAND_TYPES.START_STATEMENT) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const progress = room.progress || {};
        const scored = progress.scoredCount || 0;
        const required = progress.requiredScoreCount || 0;
        if (required <= 0 || scored < required) {
          return fail(ERR.INVALID_TRANSITION, "\u8BC4\u5206\u672A\u5B8C\u6210");
        }
        const workflow = {
          ...room.workflow || {},
          mode: "PARTNER",
          step: "STATEMENT",
          legacyPage: "statement"
        };
        const next = {
          ...room,
          lifecycle: LIFECYCLE.ACTIVE,
          status: "STARTED",
          workflow,
          revision: room.revision + 1,
          domainRevisions: {
            ...room.domainRevisions || emptyDomainRevisions(),
            session: (room.domainRevisions && room.domainRevisions.session || 0) + 1
          },
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["session"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { startedStatement: true, legacyPage: "statement" }
        });
      }
      if (type === COMMAND_TYPES.ADVANCE_TURN) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const seats = Object.keys(room.seatMap || {}).map((k) => parseInt(k, 10)).filter((n) => Number.isFinite(n)).sort((a, b) => a - b);
        if (!seats.length) return fail(ERR.INVALID_TRANSITION, "\u65E0\u6709\u6548\u5E2D\u4F4D");
        const current = room.workflow && room.workflow.activeSeatNo != null ? Number(room.workflow.activeSeatNo) : seats[0];
        const idx = seats.indexOf(current);
        const nextSeat = seats[(idx >= 0 ? idx + 1 : 0) % seats.length];
        const wrapped = idx >= 0 && nextSeat === seats[0] && current === seats[seats.length - 1];
        const roundNo = (room.workflow && room.workflow.roundNo || 1) + (wrapped ? 1 : 0);
        const turnId = `turn_r${roundNo}_s${nextSeat}`;
        const workflow = {
          ...room.workflow || {},
          mode: "PARTNER",
          step: "TURN_ACTIVE",
          activeSeatNo: nextSeat,
          roundNo,
          turnId,
          legacyPage: "gamepage"
        };
        const progress = {
          scoredCount: 0,
          requiredScoreCount: Math.max(0, seats.length - 1),
          votedCount: 0,
          requiredVoteCount: 0,
          turnId
        };
        const next = {
          ...room,
          workflow,
          progress,
          revision: room.revision + 1,
          domainRevisions: {
            ...room.domainRevisions || emptyDomainRevisions(),
            session: (room.domainRevisions && room.domainRevisions.session || 0) + 1,
            scores: (room.domainRevisions && room.domainRevisions.scores || 0) + 1
          },
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["session", "scores"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: {
            advancedTurn: true,
            activeSeatNo: nextSeat,
            roundNo,
            turnId,
            legacyPage: "gamepage"
          }
        });
      }
      if (type === COMMAND_TYPES.LEAVE_ROOM) {
        if (isHost) {
          return fail(ERR.HOST_CANNOT_LEAVE);
        }
        const seatMap = { ...room.seatMap };
        delete seatMap[String(actorSeat)];
        const membersByUserId = { ...room.membersByUserId || {} };
        delete membersByUserId[actorUserId];
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          seatMap,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { left: true, freedSeatNo: actorSeat }
        });
      }
      if (type === COMMAND_TYPES.DISSOLVE_ROOM) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        const next = {
          ...room,
          lifecycle: LIFECYCLE.DISSOLVED,
          status: "DISSOLVED",
          seatMap: {},
          membersByUserId: {},
          domainRevisions: {
            ...room.domainRevisions || emptyDomainRevisions(),
            members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
          },
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { dissolved: true }
        });
      }
      if (type === COMMAND_TYPES.REORDER_SEATS) {
        if (!isHost) return fail(ERR.HOST_REQUIRED);
        if (room.lifecycle !== LIFECYCLE.LOBBY) {
          return fail(ERR.INVALID_TRANSITION, "\u4EC5\u5927\u5385\u53EF\u8C03\u6574\u5E2D\u4F4D");
        }
        const order = Array.isArray(payload.userIdOrder) ? payload.userIdOrder : null;
        if (!order || !order.length) {
          return fail(ERR.INVALID_ARGUMENT, "userIdOrder \u5FC5\u586B");
        }
        const currentIds = Object.values(room.seatMap || {}).map(String).sort();
        const nextIds = order.map(String).sort();
        if (currentIds.length !== nextIds.length || currentIds.join(",") !== nextIds.join(",")) {
          return fail(ERR.INVALID_ARGUMENT, "\u5E2D\u4F4D\u6210\u5458\u96C6\u5408\u5FC5\u987B\u4E00\u81F4");
        }
        if (order.length > MAX_SEATS) {
          return fail(ERR.INVALID_ARGUMENT, "\u5E2D\u4F4D\u8D85\u51FA\u4E0A\u9650");
        }
        const seatMap = {};
        const membersByUserId = { ...room.membersByUserId || {} };
        order.forEach((uid, idx) => {
          const seatNo = idx + 1;
          seatMap[String(seatNo)] = uid;
          if (membersByUserId[uid]) {
            membersByUserId[uid] = {
              ...membersByUserId[uid],
              seatNo,
              role: seatNo === 1 ? "HOST" : "PLAYER"
            };
          }
        });
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          seatMap,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { reordered: true }
        });
      }
      if (type === COMMAND_TYPES.UPDATE_MEMBER_PROFILE) {
        const membersByUserId = { ...room.membersByUserId || {} };
        const prev = membersByUserId[actorUserId];
        if (!prev) return fail(ERR.NOT_MEMBER);
        const nextMember = { ...prev };
        if (isNonEmptyString(payload.nickName)) {
          nextMember.nickName = String(payload.nickName).trim();
        }
        if (payload.avatarUrl !== void 0) {
          nextMember.avatarUrl = payload.avatarUrl || null;
        }
        membersByUserId[actorUserId] = nextMember;
        const domainRevisions = {
          ...room.domainRevisions || emptyDomainRevisions(),
          members: (room.domainRevisions && room.domainRevisions.members || 0) + 1
        };
        const next = {
          ...room,
          membersByUserId,
          domainRevisions,
          revision: room.revision + 1,
          updatedAt: ts
        };
        return okResult({
          commandId,
          appliedRevision: next.revision,
          changedDomains: ["members"],
          room: next,
          head: buildHead(next, actorUserId),
          effects: { profileUpdated: true }
        });
      }
      return fail(ERR.INVALID_ARGUMENT, `\u672A\u5B9E\u73B0\u7684\u547D\u4EE4: ${type}`);
    }
    module2.exports = {
      executeCommand,
      buildHead,
      buildCapabilities,
      projectSnapshot,
      projectMembersDomain,
      authorizeRoomRead,
      allocateSeatNo,
      findSeatNo,
      createRoomAggregate
    };
  }
});

// packages/room-application/index.js
var require_room_application = __commonJS({
  "packages/room-application/index.js"(exports2, module2) {
    "use strict";
    var {
      COMMAND_TYPES,
      ERR,
      fail,
      okResult,
      validateCommandEnvelope,
      isNonEmptyString
    } = require_room_contracts();
    var {
      executeCommand,
      buildHead,
      projectSnapshot,
      authorizeRoomRead
    } = require_room_domain();
    function createRoomApplication2(repo) {
      if (!repo || typeof repo.loadRoom !== "function") {
        throw new Error("RoomRepository required");
      }
      async function execute(rawEnvelope, actorContext) {
        const actorUserId = actorContext && actorContext.userId;
        if (!actorUserId) {
          return fail(ERR.UNAUTHENTICATED);
        }
        const validated = validateCommandEnvelope(rawEnvelope);
        if (!validated.ok) return validated;
        const envelope = validated.envelope;
        const existingCmd = await repo.loadCommand(envelope.commandId);
        if (existingCmd) {
          if (String(existingCmd.actorUserId) !== String(actorUserId) || existingCmd.roomId && envelope.roomId && String(existingCmd.roomId) !== String(envelope.roomId)) {
            return fail(ERR.COMMAND_ID_CONFLICT);
          }
          return existingCmd.result;
        }
        let room = null;
        if (envelope.type !== COMMAND_TYPES.CREATE_ROOM) {
          room = await repo.loadRoom(envelope.roomId);
        }
        const domainResult = executeCommand({
          room,
          envelope,
          actorUserId,
          roomIdFactory: repo.generateRoomId ? () => repo.generateRoomId() : void 0,
          now: Date.now()
        });
        if (!domainResult.ok) {
          return {
            ...domainResult,
            commandId: envelope.commandId
          };
        }
        await repo.persistRoom(domainResult.room, domainResult.effects || {});
        const success = okResult({
          commandId: envelope.commandId,
          appliedRevision: domainResult.appliedRevision,
          changedDomains: domainResult.changedDomains || [],
          head: domainResult.head || buildHead(domainResult.room, actorUserId),
          effects: domainResult.effects || {},
          roomId: domainResult.room.roomId
        });
        await repo.saveCommandResult({
          commandId: envelope.commandId,
          actorUserId,
          roomId: domainResult.room.roomId,
          type: envelope.type,
          result: success
        });
        return success;
      }
      async function readHead(roomId, actorContext) {
        const actorUserId = actorContext && actorContext.userId;
        if (!isNonEmptyString(roomId)) {
          return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
        }
        const room = await repo.loadRoom(roomId);
        const auth = authorizeRoomRead(room, actorUserId);
        if (!auth.ok) return auth;
        return okResult({ head: buildHead(auth.room, actorUserId) });
      }
      async function readSnapshot(roomId, actorContext, request) {
        const actorUserId = actorContext && actorContext.userId;
        if (!isNonEmptyString(roomId)) {
          return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
        }
        const room = await repo.loadRoom(roomId);
        const auth = authorizeRoomRead(room, actorUserId);
        if (!auth.ok) return auth;
        const domains = request && request.domains || ["members"];
        let extraDomainData = {};
        if (typeof repo.loadDomainData === "function") {
          extraDomainData = await repo.loadDomainData(roomId, domains);
        }
        const snapshot = projectSnapshot(auth.room, {
          actorUserId,
          domains,
          clientDomainRevisions: request && request.domainRevisions || {},
          extraDomainData
        });
        return okResult({ snapshot, head: buildHead(auth.room, actorUserId) });
      }
      async function heartbeat(roomId, actorContext, payload) {
        const actorUserId = actorContext && actorContext.userId;
        if (!isNonEmptyString(roomId)) {
          return fail(ERR.INVALID_ARGUMENT, "roomId \u5FC5\u586B");
        }
        if (!isNonEmptyString(actorUserId)) {
          return fail(ERR.UNAUTHENTICATED);
        }
        const room = await repo.loadRoom(roomId);
        const auth = authorizeRoomRead(room, actorUserId);
        if (!auth.ok) return auth;
        if (typeof repo.upsertPresence !== "function") {
          return fail(ERR.DEPENDENCY_UNAVAILABLE, "presence store unavailable");
        }
        const row = await repo.upsertPresence({
          roomId,
          userId: actorUserId,
          deviceSessionId: payload && payload.deviceSessionId
        });
        return okResult({
          presence: row,
          revision: auth.room.revision
        });
      }
      return { execute, readHead, readSnapshot, heartbeat };
    }
    function createInMemoryRoomRepository(options) {
      const rooms = /* @__PURE__ */ new Map();
      const commands = /* @__PURE__ */ new Map();
      const presence = /* @__PURE__ */ new Map();
      const domainExtras = /* @__PURE__ */ new Map();
      let seq = 1e7;
      return {
        rooms,
        commands,
        presence,
        domainExtras,
        generateRoomId() {
          if (options && typeof options.generateRoomId === "function") {
            return options.generateRoomId();
          }
          seq += 1;
          return String(seq);
        },
        async loadRoom(roomId) {
          const room = rooms.get(roomId);
          return room ? JSON.parse(JSON.stringify(room)) : null;
        },
        async loadCommand(commandId) {
          return commands.get(commandId) || null;
        },
        async saveCommandResult(row) {
          commands.set(row.commandId, row);
        },
        async persistRoom(room) {
          rooms.set(room.roomId, JSON.parse(JSON.stringify(room)));
        },
        async loadDomainData(roomId, domains) {
          const bag = domainExtras.get(roomId) || {};
          const out = {};
          (domains || []).forEach((d) => {
            if (d !== "members" && Object.prototype.hasOwnProperty.call(bag, d)) {
              out[d] = bag[d];
            }
          });
          return out;
        },
        async upsertPresence({ roomId, userId, deviceSessionId }) {
          const key = `${roomId}:${userId}:${deviceSessionId || "default"}`;
          const row = {
            roomId,
            userId,
            deviceSessionId: deviceSessionId || "default",
            lastSeenAt: Date.now(),
            online: true
          };
          presence.set(key, row);
          return row;
        },
        async listPresence(roomId) {
          return [...presence.values()].filter((p) => p.roomId === roomId);
        }
      };
    }
    module2.exports = {
      createRoomApplication: createRoomApplication2,
      createInMemoryRoomRepository
    };
  }
});

// packages/room-cloudbase-adapter/index.js
var require_room_cloudbase_adapter = __commonJS({
  "packages/room-cloudbase-adapter/index.js"(exports2, module2) {
    "use strict";
    var { MAX_SEATS } = require_room_contracts();
    var ROOMS = "rooms";
    var MEMBERS = "roomMembers";
    var COMMANDS = "roomCommands";
    var PRESENCE = "roomPresence";
    var SCORES = "roomScores";
    var MESSAGES = "roomMessages";
    var VOTES = "roomVotes";
    var ARTIFACTS = "roomArtifacts";
    function createCloudBaseRoomRepository2(deps) {
      const db2 = deps.db;
      if (!db2) throw new Error("db required");
      async function generateRoomId(maxRetry) {
        const retries = maxRetry || 5;
        for (let i = 0; i < retries; i += 1) {
          const roomId = String(Math.floor(1e7 + Math.random() * 9e7));
          const exist = await db2.collection(ROOMS).where({ roomId }).limit(1).get();
          if (!exist.data || !exist.data.length) return roomId;
        }
        return String(Math.floor(1e7 + Math.random() * 9e7));
      }
      function toAggregate(roomDoc, memberDocs) {
        if (!roomDoc) return null;
        const membersByUserId = {};
        const seatMap = roomDoc.seatMap && typeof roomDoc.seatMap === "object" ? { ...roomDoc.seatMap } : {};
        (memberDocs || []).forEach((m) => {
          if (!m || !m.userId) return;
          const seatNo = m.playerIndex != null ? Number(m.playerIndex) : null;
          membersByUserId[m.userId] = {
            userId: m.userId,
            seatNo,
            role: m.role === "GOD" || m.role === "HOST" ? "HOST" : "PLAYER",
            nickName: m.nickName || `\u73A9\u5BB6${seatNo || ""}`,
            avatarUrl: m.avatarUrl || null,
            avatarColor: m.avatarColor || "#5EC159",
            avatarIndex: m.avatarIndex != null ? m.avatarIndex : null,
            joinedAt: m.joinedAt || null,
            _id: m._id
          };
          if (seatNo && !seatMap[String(seatNo)]) {
            seatMap[String(seatNo)] = m.userId;
          }
        });
        if (!Object.keys(seatMap).length) {
          Object.values(membersByUserId).forEach((m) => {
            if (m.seatNo) seatMap[String(m.seatNo)] = m.userId;
          });
        }
        return {
          _id: roomDoc._id,
          roomId: roomDoc.roomId,
          schemaVersion: roomDoc.schemaVersion || 1,
          protocolVersion: roomDoc.protocolVersion || 1,
          lifecycle: roomDoc.lifecycle || (roomDoc.status === "DISSOLVED" ? "DISSOLVED" : "LOBBY"),
          status: roomDoc.status || "CREATED",
          hostUserId: roomDoc.hostUserId || roomDoc.creatorId,
          creatorId: roomDoc.creatorId || roomDoc.hostUserId,
          seatMap,
          activeSessionId: roomDoc.activeSessionId || null,
          revision: roomDoc.revision != null ? roomDoc.revision : 0,
          workflow: roomDoc.workflow || null,
          domainRevisions: roomDoc.domainRevisions || null,
          progress: roomDoc.progress || null,
          workshopName: roomDoc.workshopName || "\u8111\u66B4\u5DE5\u4F5C\u574A",
          membersByUserId,
          createdAt: roomDoc.createdAt,
          updatedAt: roomDoc.updatedAt
        };
      }
      async function loadRoom(roomId) {
        const roomRes = await db2.collection(ROOMS).where({ roomId }).limit(1).get();
        if (!roomRes.data || !roomRes.data.length) return null;
        const roomDoc = roomRes.data[0];
        const membersRes = await db2.collection(MEMBERS).where({ roomId }).limit(MAX_SEATS).get();
        return toAggregate(roomDoc, membersRes.data || []);
      }
      async function loadCommand(commandId) {
        try {
          const res = await db2.collection(COMMANDS).doc(commandId).get();
          return res && res.data ? res.data : null;
        } catch (e) {
          return null;
        }
      }
      async function saveCommandResult(row) {
        const now = Date.now();
        await db2.collection(COMMANDS).doc(row.commandId).set({
          data: {
            commandId: row.commandId,
            actorUserId: row.actorUserId,
            roomId: row.roomId,
            type: row.type,
            result: row.result,
            createdAt: now,
            updatedAt: now
          }
        });
      }
      async function persistRoom(room, effects) {
        const now = room.updatedAt || Date.now();
        const roomFields = {
          roomId: room.roomId,
          schemaVersion: room.schemaVersion,
          protocolVersion: room.protocolVersion,
          lifecycle: room.lifecycle,
          status: room.status,
          hostUserId: room.hostUserId,
          creatorId: room.creatorId || room.hostUserId,
          seatMap: room.seatMap,
          activeSessionId: room.activeSessionId,
          revision: room.revision,
          workflow: room.workflow,
          domainRevisions: room.domainRevisions,
          progress: room.progress,
          workshopName: room.workshopName,
          updatedAt: now
        };
        if (effects && effects.created) {
          roomFields.createdAt = room.createdAt || now;
          await db2.collection(ROOMS).add({ data: roomFields });
        } else if (room._id) {
          await db2.collection(ROOMS).doc(room._id).update({ data: roomFields });
        } else {
          await db2.collection(ROOMS).where({ roomId: room.roomId }).update({ data: roomFields });
        }
        if (effects && effects.dissolved) {
          const all = await db2.collection(MEMBERS).where({ roomId: room.roomId }).limit(20).get();
          for (const m of all.data || []) {
            await db2.collection(MEMBERS).doc(m._id).remove();
          }
          return;
        }
        const existing = await db2.collection(MEMBERS).where({ roomId: room.roomId }).limit(20).get();
        const byUser = {};
        (existing.data || []).forEach((m) => {
          byUser[m.userId] = m;
        });
        const desiredIds = new Set(Object.keys(room.membersByUserId || {}));
        for (const userId of Object.keys(byUser)) {
          if (!desiredIds.has(userId)) {
            await db2.collection(MEMBERS).doc(byUser[userId]._id).remove();
          }
        }
        for (const userId of desiredIds) {
          const m = room.membersByUserId[userId];
          const data = {
            roomId: room.roomId,
            userId,
            role: m.role === "HOST" ? "GOD" : "PLAYER",
            nickName: m.nickName,
            avatarUrl: m.avatarUrl,
            avatarColor: m.avatarColor,
            avatarIndex: m.avatarIndex,
            playerIndex: m.seatNo,
            joinedAt: m.joinedAt || now,
            lastSeenAt: now
          };
          if (byUser[userId]) {
            await db2.collection(MEMBERS).doc(byUser[userId]._id).update({ data });
          } else {
            await db2.collection(MEMBERS).add({ data });
          }
        }
        if (effects && effects.scoreUpsert && room.scoresByKey && effects.scoreKey) {
          const row = room.scoresByKey[effects.scoreKey];
          if (row) {
            const docId = `${room.roomId}_${row.turnId}_${row.scorerUserId}`.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 128);
            try {
              await db2.collection(SCORES).doc(docId).set({
                data: {
                  roomId: room.roomId,
                  turnId: row.turnId,
                  userId: row.scorerUserId,
                  currentPlayerIndex: row.activeSeatNo,
                  score: row.score,
                  updatedAt: row.updatedAt,
                  createdAt: row.updatedAt
                }
              });
            } catch (e) {
              console.warn("persist score failed", e);
            }
          }
        }
        if (effects && effects.messageAppended && Array.isArray(room.messages)) {
          const msg = room.messages.find((m) => m && m.id === effects.messageId);
          if (msg) {
            try {
              await db2.collection(MESSAGES).add({
                data: {
                  roomId: room.roomId,
                  messageId: msg.id,
                  text: msg.text,
                  at: msg.at,
                  round: msg.round,
                  phase: msg.phase,
                  anonKey: msg.anonKey
                }
              });
            } catch (e) {
              console.warn("persist message failed", e);
            }
          }
        }
        if (effects && effects.voteUpsert && room.votesByKey && effects.voteKey) {
          const row = room.votesByKey[effects.voteKey];
          if (row) {
            const docId = `${row.voteSessionId}_${row.voterUserId}`.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 128);
            try {
              await db2.collection(VOTES).doc(docId).set({
                data: {
                  roomId: room.roomId,
                  voteSessionId: row.voteSessionId,
                  userId: row.voterUserId,
                  seatNo: row.seatNo,
                  vote: row.vote,
                  at: row.at
                }
              });
            } catch (e) {
              console.warn("persist vote failed", e);
            }
          }
        }
        if (effects && effects.artifactAppended && Array.isArray(room.artifacts)) {
          const art = room.artifacts.find((a) => a && a.operationId === effects.operationId);
          if (art) {
            try {
              await db2.collection(ARTIFACTS).add({
                data: {
                  roomId: room.roomId,
                  ...art
                }
              });
            } catch (e) {
              console.warn("persist artifact failed", e);
            }
          }
        }
      }
      async function loadDomainData(roomId, domains) {
        const out = {};
        const wanted = domains || [];
        if (wanted.includes("scores")) {
          try {
            const res = await db2.collection(SCORES).where({ roomId }).limit(200).get();
            out.scores = res.data || [];
          } catch (e) {
            out.scores = [];
          }
        }
        return out;
      }
      async function upsertPresence({ roomId, userId, deviceSessionId }) {
        const device = deviceSessionId || "default";
        const docId = `${roomId}_${userId}_${device}`.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 128);
        const now = Date.now();
        const data = {
          roomId,
          userId,
          deviceSessionId: device,
          lastSeenAt: now,
          online: true,
          updatedAt: now
        };
        try {
          await db2.collection(PRESENCE).doc(docId).set({ data });
        } catch (e) {
          await db2.collection(PRESENCE).add({ data: { ...data, _fallbackId: docId } });
        }
        return data;
      }
      async function listPresence(roomId) {
        const res = await db2.collection(PRESENCE).where({ roomId }).limit(50).get();
        return res.data || [];
      }
      return {
        generateRoomId,
        loadRoom,
        loadCommand,
        saveCommandResult,
        persistRoom,
        loadDomainData,
        upsertPresence,
        listPresence
      };
    }
    module2.exports = {
      createCloudBaseRoomRepository: createCloudBaseRoomRepository2
    };
  }
});

// cloudfunctions/roomPresence/src/entry.js
var cloud = require("wx-server-sdk");
var { createRoomApplication } = require_room_application();
var { createCloudBaseRoomRepository } = require_room_cloudbase_adapter();
cloud.init({ env: cloud.DYNAMIC_CURRENT_ENV });
var db = cloud.database();
var app = createRoomApplication(createCloudBaseRoomRepository({ db, cloud }));
exports.main = async (event) => {
  const wxContext = cloud.getWXContext();
  const userId = wxContext.FROM_OPENID || wxContext.OPENID || "";
  const roomId = event && event.roomId;
  try {
    return await app.heartbeat(roomId, { userId }, {
      deviceSessionId: event && event.deviceSessionId
    });
  } catch (e) {
    console.error("roomPresence error", e);
    return {
      ok: false,
      errCode: e.errCode || e.code || "INTERNAL_ERROR",
      errMsg: e.errMsg || e.message || "roomPresence failed"
    };
  }
};
